### ISSUE TITLE
modify the look of the vectors on the map

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#1]
I think the vectors might look better if they were longer and not so wide, or at least so that the tail was something like 2 or 3 times the length of the head.  Also, possibly the line width might be reduced just slightly.

**Comment by fspataro** [comment]
Does it make any sense to use standard weather map wind arrows? Could have an option to choose between the two styles? http://www.hpc.ncep.noaa.gov/dailywxmap/gifimages/windspeed.gif

**Comment by jforthofer** [comment]
I'm not really a fan of the weather service wind barbs for our applications because they are based on "knots" rather than "mph".  Our typical users are not very familiar with knots.  For example, an arrow with 4 full barbs represents 40 knots (range is 38-42 knots), but this is 44-49 mph, which I would never remember...
