### ISSUE TITLE
guidance on selecting domain and initiating the run

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#10]
It is a little confusing having the map be the first thing that shows up. We should have a start page or something that gives some guidance on how to proceed after the splash screen exits. Something like this flow might work:

1. Splash screen
2. Start page/message box with some instructions on how to use the map to select your area and start the run. This box should only be dismissed after the user clicks a "Got it" button.
3. Full screen map for selecting domain. Once a bounding box appears after a long click, a button appears that says "Start run" or something to take the user to the run creation page. The user can click on this after they are happy with the domain defined by the bounding box.

Maybe there should also be a help tab that can be selected at anytime to display the info in 2 in case the user gets confused at some point.

**Comment by fspataro** [comment]
Agreed, we'll add help page.
