### ISSUE TITLE
Better message when job submitted with no Internet connection

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#100]
When a job is submitted when the Internet connection is very poor, the user receives a message that says:
Error
Server Error: undefined
OK

I'm assuming this is happening because of a bad connection...  It would be better if we could give a good message telling the user their Internet connection is bad.

**Comment by CorbyHarkonnen** [comment]
new message if the error comes back 'undefined':

'There appears to be an error communicating with the server, please try again shortly or connect to WiFi and try submitting again.'
