### ISSUE TITLE
Incomplete download

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#101]
We ran into a situation where it seems like a run was not completely downloaded due to poor/intermittent Internet connection.  The download progress bar just hung for a long time, so WindNinja was closed and then reopened.  The button for the run was now showing "Plot" as if the run had been successfully downloaded.  When the plot button was pushed nothing was plotted.  I believe this was due to only a partial download.  Is it possible to check to see if the download is complete before switching the button to "Plot"?  If not, maybe the button could stay at "Download" and when clicked the run could be re-downloaded?  Other ideas?

**Comment by CorbyHarkonnen** [comment]
I tweaked how runs are marked as 'downloaded' in 1.0.3, so this should fix the issue of a run not downloading completely, but still showing the 'Plot' button. I will need external testing to verify, as I have not been able to reliably reproduce this on my devices
