### ISSUE TITLE
"Plot" button text not showing fully

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#102]
This occurred on a Samsung Tablet SM-T230NU using Android version 4.4.2.  The "Plot" button's text just showed "Pl.."  as if there wasn't enough screen space to print out the whole text.  Can this be fixed?

**Comment by jforthofer** [comment]
I just confirmed that this is still a problem on the device mentioned above.  The screenshot below shows the problem... the "Status" button in this case just says "Stat.." as if the text got cut off.

![screenshot_2017-02-07-14-01-09](https://cloud.githubusercontent.com/assets/3695983/22711580/f47aedfc-ed3e-11e6-889c-4f45db6c184f.png)

**Comment by CorbyHarkonnen** [comment]
Jason,

Can you check to see if the font size is set to something other than ‘small’ on that device? It should be under ‘Settings’ --> Display --> font, or ‘Accessibility’ --> vision --> font or someplace similar? Thanks!

Tory Weber
Software Engineer, Systems Engineer
GCS
115 S 4th ST W Missoula MT 59801
Cell (406) 274-6694
tweber@yourdatasmarter.com<mailto:tweber@yourdatasmarter.com> • www.yourdatasmarter.com<http://www.yourdatasmarter.com/>

**Comment by jforthofer** [comment]
It is set to "small".

**Comment by CorbyHarkonnen** [comment]
Hmm. Ok thanks. I’ll have to do some more digging on this then. I’ve moved this issue to the 1.1 release for the time being.

Tory Weber
Software Engineer, Systems Engineer
GCS
115 S 4th ST W Missoula MT 59801
Cell (406) 274-6694
tweber@yourdatasmarter.com<mailto:tweber@yourdatasmarter.com> • www.yourdatasmarter.com<http://www.yourdatasmarter.com/>
