### ISSUE TITLE
Modify text in registration email

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#103]
Currently the email the user receives for registering WindNinja-mobile is:

Please verify this account by submitting the confirmation code at the following URL:

http://windninja.wfmrda.org/services/registration/confirm?code=wpLDqBLDnMKjJsKWw4R1bcO1NF_DnsK6w4fDrcONwpYjw4I%3D%3A8016de03ba34dcfe34103fe5ef0978a4f46e912a81de55da6f644109d04f172e%3A1466092055&f=html

This code is valid for 10 minutes.

The "confirmation code" part is a little confusing, even to me.  It makes it seem like you'll need to type in some code after you click on the link.  Can we change the text to read:

Welcome to WindNinja-mobile! Please click the link below to complete your registration:

http://windninja.wfmrda.org/services/registration/confirm?code=wpLDqBLDnMKjJsKWw4R1bcO1NF_DnsK6w4fDrcONwpYjw4I%3D%3A8016de03ba34dcfe34103fe5ef0978a4f46e912a81de55da6f644109d04f172e%3A1466092055&f=html

This link is valid for 10 minutes.

**Comment by nwagenbrenner** [comment]
We should change this soon. We've gotten feedback from several users who were confused by the email or weren't able to get to the link in time. It's also not clear what happens if the user can't get to the link before it expires.
