### ISSUE TITLE
GeoMac layer not working correctly

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#104]
Seems like the GeoMac layer is not plotting the most recent fires shown on the GeoMac web site.  For example, there are several fires in Arizona and New Mexico right now, but they don't show up in our app.  See the GeoMac web site here:
http://www.geomac.gov/viewer/viewer.shtml
There fire's shown here should, ideally, show up in the app.

**Comment by fspataro** [comment]
Short answer:  current fires and current fire perimeters are now layer id: 23 and 24 not 25 and 26.  

Long answer:  The WMS capabilities for this service uses the "index" as the layer identifier not a unique text string.  So when the service authors add, remove, or reorder layers in the service the "index" identifier changes and the layers that we ask to be displayed in the mobile app are out of sync.  In this case it looks like at least two layers were removed as there are only 24 layers in the service now. 

http://wildfire.cr.usgs.gov/arcgis/services/geomac_dyn/MapServer/WMSServer?service=wms&request=GetCapabilities

This will continue to be an issue unless the service authors make a change to the way they publish this service. I submitted a friendly email to the help link to use the text identifier option but I'm not expecting any changes.  I'll add a another enhancement item to make figuring out the layers more robust and dynamic but that will require a full round trip request to the geomac server during app initialize and code to parse the capbilities xml to look for specific text in the layers.  Even this wouldn't be completely foolproof.

**Comment by jforthofer** [comment]
Hate when that happens...  we've had similar problems in the desktop version of WindNinja when we have to rely on 3rd party data that seems to randomly change format slightly.  Thanks for getting to the bottom of this, I assume you've fixed the layer numbers for now?

**Comment by CorbyHarkonnen** [comment]
fixed (for now) in 0.2.7

**Comment by fspataro** [comment]
Looks like I convinced the GeoMac staff to change the WMS capabilities from the "index" identifier to the "layer name" identifier so this is probably broken again now but once we update to the name identifier it should be less likely to break down the line.

**Comment by CorbyHarkonnen** [comment]
I'll get the code changed to use the layer name instead of the index.

**Comment by CorbyHarkonnen** [comment]
updated code to use layer names instead of indexes. verified working
