### ISSUE TITLE
Enhance geomac layer to dynamically read wms capabilities xml in order to find layers to display

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#105]
See discussion in #104

**Comment by fspataro** [comment]
The GeoMac service is now using "layer names" as the WMS capability identifier so this might not be necessary anymore. Other than possibly reporting an nice user message if the layer is not in the service but that really shouldn't happen.

**Comment by CorbyHarkonnen** [comment]
closing this bug as it appears to be fixed with the 'layer names' update to the map service
