### ISSUE TITLE
Google Play store can't load app onto my new phone

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#106]
When I go to the listing on the Google Play store, I cannot select my new phone to load the app onto.  It seems that Google Play thinks my new phone is not compatible with the WindNinja app.  The new phone specs are:
SAMSUNG-SM-G930V
Android version 6.0.1

My old phone does show up as being able to load the app:
SAMSUNG-SM-G900V
Android 5.0

**Comment by nwagenbrenner** [comment]
That's exactly what I said in my email 10 minutes ago. cc'd Fred and Sarah. It's not clear if this is a store listing issue or a problem in the apk.

**Comment by jforthofer** [comment]
If the version that's on Google Play is still 0.2.6, then I can confirm that the signed apk file from here:

http://geo.yourdatasmarter.com/usfs/WindNinja/Mobile/WindNinja-Mobile-0.2.6.apk

DOES work on my new phone.  If this is true, it seems like it might point to a problem with the Play store listing...?  But then again I'm not sure how Android and Play do the checking for version compatibility, etc.

**Comment by nwagenbrenner** [comment]
https://support.google.com/googleplay/android-developer/answer/1286017?hl=en

https://developer.android.com/guide/topics/manifest/manifest-intro.html

**Comment by CorbyHarkonnen** [comment]
looks like i forgot to up the maximum API level for android, it was set for 5.1 previously. I will try to change this so we're not targeting a maximum API, only a minimum. (currently, the lowest version of Android we're allowing is 4.0)

**Comment by nwagenbrenner** [comment]
We can upload a new APK for testing in Google Play anytime. Jason, do you want to just get a new APK with this device compatibility fix for testing? Or wait for 1.0.0? I would suggest we upload a new APK as soon as possible with just this fix so we can have a more thorough testing...

**Comment by jforthofer** [comment]
I agree, upload the fix now so we can continue with testing.

**Comment by CorbyHarkonnen** [comment]
I'll do a build today with this fix and get it uploaded so you can sign it and put it in the store.

**Comment by CorbyHarkonnen** [comment]
fixed in 0.2.7

**Comment by nwagenbrenner** [comment]
We uploaded the new APK (0.2.7.0), but when I try to install it from the store it still tells me it's not compatible with this device:

SAMSUNG-SM-G930V
Android version 6.0.1

The store listing still reports it as requiring Android 4.0-5.0.

https://play.google.com/store/apps/details?id=gov.usda.fs.rmrs.windninja&hl=en
