### ISSUE TITLE
Quick Start edits

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#107]
Seems like this box should have an "OK" or "Got it" button to dismiss the window. Points 2 and 3 should have periods at the end of the sentence. 

It's also a little weird that the quick start appears with the registration screen. It's weird because you read the instructions about drawing an area on the map, etc., but then when you dismiss the window you're not in a place to perform those actions. Maybe we shouldn't default to the settings tab at first start up, but just go straight to the map? Other ideas?

**Comment by jforthofer** [comment]
Or maybe if it first went to the Registration page, then when that is closed the Quick Start popped up?  This would only be for the first time the user uses the app.  What do you guys think?
Another idea for an addition to the Quick Start page might be a link to a Quick Start Video on YouTube that we could make...?  Could be really useful I think, especially if we could make the video very short and concise...

**Comment by CorbyHarkonnen** [comment]
no longer opening the settings panel after registration, instead only showing the 'Quick Start' guide
