### ISSUE TITLE
script to track app usage

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#108]
We need a script to fetch and track app usage. Every time a job is submitted we should capture at least this basic info (from job.json or wherever it's easiest to get it) and dump it into a summary file:

--user/account
--job id
--date/time submitted

This info can be summarized later on to generate usage statistics, etc.

**Comment by fspataro** [comment]
The queue manager folder will give you basic counts without much effort.  It doesn't track account, but job id and date (file stamp) are captured.  So getting basic statistics can be gleamed from counting files   for a given time range and status (pending, complete, failed, etc)

**Comment by nwagenbrenner** [comment]
I added a simple script in 4261397 to capture info from job/job.json and write it to /home/ubuntu/logs/stats.log. It captures the info as soon as a new job folder is created. We can improve this later.
