### ISSUE TITLE
Clean up old jobs

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#109]
We need a plan to clean up the jobs directory. For starters, we could run a cron job that deletes all jobs older than 5 days. Forecasts would have expired by that time anyway. Let me know if this sounds okay.

**Comment by jforthofer** [comment]
Sounds good to me.

**Comment by fspataro** [comment]
This can also be easily added to the queue manager loop since it is already running a timed loop.  It could easily acquire all the "complete" job ids for a run and kick-off a cleanup script.

**Comment by nwagenbrenner** [comment]
I added a script in c3c7306 that should do what we want. Doesn't matter to me if we use cron or the queue manager.

**Comment by fspataro** [comment]
Actually the point-six job used by the client app for example data is id:  23becdaadf7c4ec2993497261e63d813 not the 1x111.... jobs. Those are test jobs for debugging and can be cleanup up. 

If the 23be.... folder is deleted the point-six example job won't be available in the client app.  It can be reloaded from the source if deleted.

**Comment by nwagenbrenner** [comment]
Updated the script in fc9361b and added as a cron job to run every day at 6 UTC.
