### ISSUE TITLE
Confirm deletion of a run

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#11]
It would probably be a good idea to confirm that the user actually wants to delete a run when they click the "Delete Run" button.  I'd be a little mad as a user if the run was deleted because I accidentally hit delete instead of the "Run Status" button I was trying to hit.

This confirmation could be done in the usual way of popping up a window asking if they user is sure they want to delete...

**Comment by CorbyHarkonnen** [comment]
I was actually contemplating adding this before I did the last build, because I have done the exact same thing on a couple of occasions. definitely easy to add..

**Comment by jforthofer** [comment]
Thanks!

**Comment by CorbyHarkonnen** [comment]
added confirmation dialog to run deletion.
