### ISSUE TITLE
Some buttons don't work when viewing options are enabled

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#112]
If the time slider or legend is displayed and you click on the settings tab and click on any of the buttons at the bottom (submit feedback/questions, help, about), nothing happens. These buttons work if the time slider and legend are not displayed.

**Comment by CorbyHarkonnen** [comment]
triggering toggling of time slider and legend when settings panel is opened/closed (the slider and legend were hiding the other buttons 'under' them, thus not allowing user to select)
