### ISSUE TITLE
Email feedback to wind.ninja.support

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#114]
Right now feedback just gets dumped to a json file in /srv/WindNinjaServer/Data/feedback. We should add a script to email wind.ninja.support@gmail.com when there is new feedback. Maybe just check it daily and dump any feedback into a single email and delete from /feedback?

**Comment by jforthofer** [comment]
+1 for that.

**Comment by fspataro** [comment]
This is already in the feedback controller, see line 156 in /windninja-server/src/windninjaweb/api.py

if it's not getting sent: is the latest code downloaded or is the email not configured correctly?

**Comment by nwagenbrenner** [comment]
It's not working. I see this 

https://github.com/firelab/windninja-mobile/blob/master/WindNinja-Server/Src/windninjaweb/api.py#L156-164

(and that is the same code that's on the server) but I'm not sure what the problem is. Email settings look good in windninjaserver.config.yaml. And email notification for job completion is working.

**Comment by fspataro** [comment]
Sorry, looks like I didn't push the feedback model template function correctly to git... try getting the latest version of windninjaweb/model.py 

you can either sudo copy that file manually to the deploy folder or run the deploy script with the app command.

**Comment by nwagenbrenner** [comment]
I copied that file over. When does this script run? How can I test it?

**Comment by fspataro** [comment]
It's part of the web controller.  It runs after the feedback record is successfully saved. Just submit a feedback from the app or api tester.

**Comment by nwagenbrenner** [comment]
Okay, if it's supposed to run as soon as feedback is submitted, then it is still not working. The feedback .json file is in /feedback.

**Comment by fspataro** [comment]
first i would restart/reload the apache process.  I've found some changes to get recompiled by the mod_wsgi process right away

Then you can change the try-catch around the email to see if some error is being generated by the mail server.  I'm getting emails thru on feedback here on my dev server:

api.py line 163:
Change 
```s
except: 
    pass
```
to 
```s
   print("sent email", file=sys.stderr)
except Exception as ex:
   print(str(ex), file=sys.stderr)
```
Be sure to import sys at the top, and then restart/reload apache service

**Comment by nwagenbrenner** [comment]
For now I just wrote a small bash script that cats any files in /feedback to an email and sends it to wind.ninja.support. I set it up to run as a cron job every night. It deletes the files in /feeback after it sends the email. If we get the feedback controller working, I'll cancel the cron job.
