### ISSUE TITLE
Add LANDFIRE as a base layer for viewing

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#115]
We should consider adding one or more of the LANDFIRE layers into the app as an (online) basemap.  The potentially useful layers in the dataset are:
- fuel model
- stand height
- canopy base height
- canopy bulk density

This would be useful to firefighters to be able to view these layers on a phone.  I don't think this ability exists in any other place.

**Comment by CorbyHarkonnen** [comment]
@jforthofer / @nwagenbrenner 

can we do a goto meeting sometime next week to go over this? I'm able to add the service no problem, but I'm not really sure which layers are actually wanted/useful.

if you could take a look at the services on a map 
[ArcGIS.com map](http://www.arcgis.com/home/webmap/viewer.html?url=https%3A%2F%2Flandfire.cr.usgs.gov%2Farcgis%2Frest%2Fservices%2FLandfire%2FUS_140%2FMapServer&source=sd)
and match with their 'products':
[Fuel](https://www.landfire.gov/fuel.php)
[Vegetation](https://www.landfire.gov/vegetation.php)

and see which ones are useful I can get this in for the next build.
I think I'll probably end up doing multiple basemaps if we want to stick with that route, as adding the fuel models and vegetation at the same time works, but is VERY busy (see image - Stuart Peak area)
![point_six](https://user-images.githubusercontent.com/10839029/26994926-41ad276e-4d27-11e7-95a7-166f8a3ef81e.PNG)

**Comment by jforthofer** [comment]
The primary layer to view would be the "US 140FBFM13" layer which is the 13 standard fire behavior fuel models layer.  Other useful layers would be:
"US 140CC" which is canopy cover
"US 140CBD" which is canopy bulk density
"US 140CBH" which is canopy base height
"US 140CH" which I assume is canopy height, although it is commonly called stand height

For some reason the last 3 above aren't plotting correctly on that map...?  Just solid grey layer...

One thing to mention, is this work (basemap plotting) getting confused with the work to actually use the LCP data to run WindNinja (where WindNinja gets the elevation and vegetation information data for the actual run from LandFire LCP)?

**Comment by jforthofer** [comment]
I was talking about #113.  That is the one I just talked with Natalie about earlier today...

**Comment by CorbyHarkonnen** [comment]
Added discussed layers (not as base maps) for viewing in 1.0.3.

If we would like to use them as actual base maps, we will need to figure out additional info that will need to be displayed (labels for cities/counties, state/county borders, roads, waterways, etc)
