### ISSUE TITLE
Feedback box problems

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#116]
When you are typing in the text box, the keyboard covers up the "cancel" and "submit" buttons so the only way to proceed when you're done typing is to hit the back button (on Android, not sure what happens on iOS).

Also, when the keyboard is displayed or hidden (by pressing the back button), the Feedback and WindNinja Mobile Settings tab screens both jump around.

**Comment by CorbyHarkonnen** [comment]
same general issue as #120, will see if I can fix this one at the same time.

**Comment by nwagenbrenner** [comment]
I see that you can scroll the open box to get to the cancel/submit buttons when the keyboard is open. Not sure if something changed or it was always like this and I just didn't notice. The screens don't seem to jump around anymore either.
