### ISSUE TITLE
Update VIIRS data

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#118]

**Comment by nwagenbrenner** [comment]
We want I-Band, it's 375 m. AF is 700 m.

**Comment by fspataro** [comment]
where is data coming from?  Didn't we already try to add this add data and their services didn't work or weren't stable or something like that?

**Comment by nwagenbrenner** [comment]
I don't remember trying to get VIIRS before. And I was just talking to Jason about this, so he doesn't remember either. Looks like we can get it here: http://activefiremaps.fs.fed.us/wms.php 

This isn't urgent, just something we should consider if we haven't already.

**Comment by fspataro** [comment]
yeah, that's one we tried before.  Those services don't support the 3857 map projection so they can't be overlaid on the basemap.  We either need to find someone serving them out with the correct projection or do that ourselves.

**Comment by fspataro** [comment]
This service supports web mercator, but only has the 'hotspots' is that want you want?
https://firms.modaps.eosdis.nasa.gov/web-services/

**Comment by jforthofer** [comment]
Yeah, I believe that is what we want...

**Comment by fspataro** [comment]
Do you want to both the 24 and 48 layer turned on or just one of them?

**Comment by jforthofer** [comment]
Let's try both for now.

**Comment by CorbyHarkonnen** [comment]
Added VIIRS data layer

**Comment by jforthofer** [comment]
Just a note for future use, Matt Jolly has made a request to RSAC (our original source for VIIRS) to add the 3857 map projection to their service.  He will let us know when it's available and I'll post that here.

**Comment by wmjolly** [comment]
RSAC has added the 3857 projection to their web mapping service.  I tested on our web mapping application and it looks like its working now.

**Comment by jforthofer** [comment]
Thanks Matt!

**Comment by fspataro** [comment]
Great, we'll load that source in the next build.

**Comment by CorbyHarkonnen** [comment]
do we have the URL for the RSAC VIIRS data?

**Comment by CorbyHarkonnen** [comment]
nevermind, I think I got the right URL. BUT, which layer do we want? looking at the WMS capabilities page, it looks like the only layer with 3857 projection is "CONUS VIIRS I Band Fire Detections". is this the correct layer to use?

[VIIRS I Band Capabilities](https://fsapps.nwcg.gov/afm/cgi-bin/mapserv.exe?map=conus_viirs_iband.map&%20SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities&version=1.0.0)

**Comment by nwagenbrenner** [comment]
Yeah, I think that's right.

**Comment by jforthofer** [comment]
Seems to be fixed.
