### ISSUE TITLE
Buttons resize problem- "viewing options" runs offscreen

### ISSUE THREAD

**Issue by megtracy** [firelab/windninja-mobile#119]
On iOS, the Viewing Options button doesn't fully fit on screen
![image](https://cloud.githubusercontent.com/assets/20272142/16548335/215e4414-4140-11e6-88d2-ad996488af22.png)

**Comment by nwagenbrenner** [comment]
Thanks for reporting this @megtracy. What device and version of Android are you using?

**Comment by nwagenbrenner** [comment]
Sorry, not Android, iOS.

**Comment by nwagenbrenner** [comment]
I also just realized the timestamp in that screen shot doesn't fit in its box either. "PDT" is below the box.

**Comment by CorbyHarkonnen** [comment]
renamed button to 'View Options' and resized slightly, should not get cut off anymore

**Comment by megtracy** [comment]
I'm on iOS 9.3.2

Just tried again, and still doesn't fit fully in the window. There is also a map element in the bottom left corner that is mostly off screen- not sure what it is supposed to be

**Comment by nwagenbrenner** [comment]
The icon at the bottom left is a scale bar. This and the other display problems reported in this issue should be fixed in version 1.0.0, which will hopefully be available in the app stores next week.
