### ISSUE TITLE
Discussion of slow visual processing and potential fixes

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#12]
This ticket was started to discuss the slow graphics processing of the vector outputs and potential fixes.

As Fred mentioned in an email, the new "Raster" method seems to be considerably faster than previous methods.  The downside is that the vectors are not as sharp on the edges and there is a bit of a problem at the tile boundaries where vectors appear to get cut off.

Right now, I like Fred's idea of making the new "Raster" method the default and one of the other vector methods optionally turned on in some sort of advanced settings screen.

I still wonder if this could be made better...  although I recognize GCS has invested considerable time here.  How much time would it take to test out a raster method with no tiling (meaning no resampling of the vectors for different zoom levels)?  This would be similar to the geoPDF Kyle made earlier as a test and we viewed in the Avenza App.  The vectors here had very sharp edges...  I'm not sure if these were raster or vector since I suppose either could be in a geoPDF, right?  Maybe we should have a phone call at some point to discuss this...

**Comment by CorbyHarkonnen** [comment]
unfortunately the speed issue with drawing the vectors comes from the limited hardware available on phones. I have the exact same code running in a web app on my development machine, and the vectors draw incredibly faster. I did some timing checks between the two versions and removed as much extra 'fluff' as possible when creating/redrawing the vectors, but even on a brand new octa-core phone (Galaxy S6 Edge and Note 4), it still runs much slower than the standard web app version, I don't believe there is much else we could do to speed this up on phone hardware. A sit-down discussion would probably be best so we can go over all the options and the pros/cons of each.

**Comment by jforthofer** [comment]
Thanks for the thoughts Corby...
I guess in my mind I still keep going back to viewing the geoPDF in Avenza and how crisp the vectors are and how fast the graphics processing is.  I realize this is a bit different than what we have done with the WindNinja app so far, since Avenza is basically just displaying an image.
If you look at a regular picture on your phone (like a .jpg or .png), you can zoom and pan very quickly.  That must be the way the graphic processing is happening in Avenza, and must be fairly different from the mapping apis you are using?

As a side note here, I'm hoping we can have WindNinja outputing geoPDFs withing the next couple of months (the student that did 75% of the geoPDF work earlier will have time this summer to finish it up).
