### ISSUE TITLE
Settings tab hides/unhides when text boxes are selected

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#120]
If you open the settings tab and click on one of the text boxes (Name, Email, etc.), before you can enter any text, the tab hides and then unhides before you can start typing.

**Comment by CorbyHarkonnen** [comment]
this might be a bit trickier. the close/open of the panel is due to the window size changing (because of the keyboard), thus resetting the size/scrolling of the UI elements. I'll take a look and see if I can not do the panel resize and have things still display properly

**Comment by CorbyHarkonnen** [comment]
I think I have this fixed properly, no longer toggling the panels on window resize

**Comment by nwagenbrenner** [comment]
Seems to be fixed.
