### ISSUE TITLE
Problems creating a new run when time slider or legend are displayed

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#121]
It is possible to create another run when a run is already displayed on the map. This seems fine to allow this, but there are problems creating the new run if either the time slider or legend from the current run are displayed. If either of these are displayed, you can draw a new area and select the check mark, but you cannot enter text for a run name to submit the job.

**Comment by CorbyHarkonnen** [comment]
ok. I can force closing of the slider and legend when the draw button is selected (this will also give you a bit map space back as well)

**Comment by CorbyHarkonnen** [comment]
fixed in 1.0.1

slider and legend are now hidden when the draw button is pressed
