### ISSUE TITLE
Problems with the Point Six test case

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#122]
I tried to create a new run while the Point Six case was plotted on the map. I ran into the issue described in #121 so went back to the Runs tabs to clear the vectors. But when I navigated back to the Runs tab, I wasn't able to open the Point Six tab. I could see it and click on it but nothing happened. I had to close and re-open the app to clear the vectors.

**Comment by CorbyHarkonnen** [comment]
does this occur with other runs loaded to the map as well, or just the Point Six run?

**Comment by nwagenbrenner** [comment]
This issue (not being able to open the case tab) only happens for the point six run.

**Comment by nwagenbrenner** [comment]
This seems to be fixed.
