### ISSUE TITLE
Satellite layer no longer works

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#125]
As of July 11, direct tile access has been discontinued.

**Comment by fspataro** [comment]
Here's the blog post:

http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

The free version allows for 15k "transactions" per month but it still requires an API key.  I don't see any definition of what a "transaction" is but from the Static Maps API documents, it appears there's no longer a tile service so every tile might count as a transaction.

**Comment by CorbyHarkonnen** [comment]
it also looks like mapquest is no longer supported in newer versions of OpenLayers (they removed the MapQuest source option), so it looks like i'll be looking for a different imagery provider anyways. anybody have a preference/suggestion?

**Comment by nwagenbrenner** [comment]
What are the options? Google? Is this something we can fix quickly for 1.0.0?

**Comment by CorbyHarkonnen** [comment]
google has the same type of restrictions on their basemaps as well (requires an api key, limited number of queries per month). There is the National Map provided by the USGS that we could use.. their available basemaps: [http://viewer.nationalmap.gov/help/3.0%20TNM%20Base%20Maps.htm] (either Imagery Only or ImageryTopo)

**Comment by nwagenbrenner** [comment]
What are the google limits? That's what we use in desktop WindNinja for our DEM fetcher, so if there are limits I guess we just haven't hit them?

**Comment by CorbyHarkonnen** [comment]
from [https://developers.google.com/maps/documentation/javascript/usage](https://developers.google.com/maps/documentation/javascript/usage) it looks like there is a limit of 25,000 queries per day for a 'standard' api key.

**Comment by fspataro** [comment]
Google is also very picky about not using their services in other API/SDKs and often change the internal guts of the service so that only their API/SDKs perform. 

The forest service has an enterprise license with Esri so that's a potential source but you'd have to jump thru their hoops for keys and registering the app etc.   They also used to have a TOU statement about excluding "dangerous activities" but they may have removed that.

**Comment by nwagenbrenner** [comment]
Okay, maybe let's just use the national map?

**Comment by fspataro** [comment]
Let's go with the NAIP service from USGS.  It only goes to level 15 but i think that's where we cut out too. Tory, the WMTS API is probably the best way to go unless there's a ArcGIS TileImageService source 

http://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/WMTS/tile/1.0.0/USGSImageryOnly/{Style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}

**Comment by fspataro** [comment]
XYZ url:  http://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/12/1575/879

**Comment by CorbyHarkonnen** [comment]
fixed in 1.0.1
using National Map (NAIP Imagery) from USGS
