### ISSUE TITLE
App freezes during run download

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#129]
This was reported by a user in Phoenix with a good WiFi signal. Here are the details:
1. I am using an iPhone 5s
2. The version is 9.3.3
3. Yes,  I have experimented with about three downloads. I have never had it download normally.
4.  The windninja app locks up and appears to just stop downloading. I am able to close WindNinja and navigate to other applications.  I have to shut the phone down to be able use WindNinja. After shutting the phone down and navigating back to the stalled download it appears that the down load finished as the WindNinja app provides the original requested product.

**Comment by jforthofer** [comment]
I would have him try one with just a couple of time steps.  I've had problems like this at times when I try to download runs with many time steps.

**Comment by ksshannon** [comment]
Well isn't that an issue too?  Or is that expected?

**Comment by nwagenbrenner** [comment]
It's definitely a bug. But I guess figuring out if it's related to the number of time steps will help us narrow down the problem. I've never seen this happen on my device, so I don't know what's causing it. The user was going to try some additional simulations today and report back.

**Comment by jforthofer** [comment]
Yes, it's a problem but we decided to not hold up the release any more...  I think there's a problem when downloads take too long (function of both connection speed and download size, ie. number of timesteps).  My guess is that the phones screen goes to sleep during the download, or something else like that.  It's a problem that we need to fix.  I saw an app the other day (I think it was a mapping app) that downloads a lot of data and they had text telling you to not let the screen sleep because the download will apparently stop.

**Comment by ksshannon** [comment]
Okay, I didn't know there was a ticket for the failed downloads.

I *think* the app state should freeze, which would cause the request to
time out.  Ideally we'd download in known blocks and resume with a range
request re downloading on the failed read. If you point me to the other
ticket, I'll add some thoughts.

**Comment by nwagenbrenner** [comment]
Possibly related to #101 and #94, although this user had a good connection and did not mention the screen going to sleep.

**Comment by nwagenbrenner** [comment]
Also, in this case the run is downloaded properly, the app just freezes in the middle and the results can't be plotted without closing and reopening the app. I feel like there may be a few different problems causing these the issues reported in these three tickets.

**Comment by jforthofer** [comment]
Kyle, sounds like a good strategy to me...  This is definitely something we need to fix, it should be bullet proof since it will be very common to have a slow connection.

**Comment by nwagenbrenner** [comment]
I don't get what you all are talking about. The issue I reported has nothing to do with a poor connection since they were on a good WiFi connection.

**Comment by jforthofer** [comment]
Maybe it's unrelated... but I've had that same problem many times when I have a bad connection, that's why I said that before.

**Comment by ksshannon** [comment]
I was trying to transition to another, unknown  ticket. My bad.

**Comment by fspataro** [comment]
Let's not speculate on the issue and get some hard facts about it:

1. iOS 9.3.3 just released (07/14/2016), so technically it's not "supported" since we've never run any tests on this environment and iOS is notorious for making tweaks to the underlying APIs.  The version of cordova used in the build might not be insync with any tweaks at this release.  

2. We have his phone specs, but we don't know what else is going on with his phone.  iOS is not good about conserving processing and multi-tasking apps.  It lets the user run just about everything at once and tries to "manage" processes.  It could easily be that his facebook app is hogging all the bandwidth and cpu.  When he runs tests for us, he should first force iOS to close out all the other running apps, if this is even possible in iOS anymore. try double tap on the home button and swipe/clear all apps but WNM.

3. Can he download the test point 6 session without issues? 

4. What are the actual parameters he's using to create runs? 

5. Have we looked at the server to see how big the zip files are that he's creating?

**Comment by nwagenbrenner** [comment]
job.json for one of the runs done by this user:

 {"status": "succeeded", "account": "breeze284@gmail.com", "name": "Run3", "messages": ["2016-08-05T20:53:05.478971 | info | job created", "2016-08-    05T20:53:08.911410+00:00 | INFO    | Initializing WindNinja Run", "2016-08-05T20:53:08.936664+00:00 | INFO    | DEM created", "2016-08-05T20:54:18.    763227+00:00 | INFO    | WindNinjaCLI executed", "2016-08-05T20:54:30.697572+00:00 | INFO    | Output converted to geojson", "2016-08-05T20:54:32.3    12630+00:00 | INFO    | TopoFire tiles compiled", "2016-08-05T20:54:45.398931+00:00 | INFO    | Output converted to raster tiles", "2016-08-05T20:5    4:45.399220+00:00 | INFO    | Complete - total processing: 0:01:36.489040"], "id": "567af160-e5c8-46bb-a3dd-5a2c6b3eb7df", "output": {"products": [    {"files": ["dem_08-05-2016_2000_27m", "dem_08-05-2016_1300_27m", "dem_08-05-2016_2100_27m", "dem_08-05-2016_1500_27m", "dem_08-05-2016_1200_27m", "    dem_08-05-2016_1400_27m", "dem_08-05-2016_1700_27m", "dem_08-05-2016_1900_27m", "dem_08-05-2016_1600_27m", "dem_08-05-2016_1800_27m"], "name": "Win    dNinja Raster Tiles", "package": "tiles.zip", "type": "raster", "format": "tiles", "data": ["dem_08-05-2016_2000_27m:10.713399", "dem_08-05-2016_13    00_27m:10.713399", "dem_08-05-2016_2100_27m:10.713399", "dem_08-05-2016_1500_27m:10.713399", "dem_08-05-2016_1200_27m:10.713399", "dem_08-05-2016_1    400_27m:10.713399", "dem_08-05-2016_1700_27m:10.713399", "dem_08-05-2016_1900_27m:10.713399", "dem_08-05-2016_1600_27m:10.713399", "dem_08-05-2016_    1800_27m:10.713399"]}, {"files": [], "package": "topofire.zip", "type": "basemap", "name": "TopoFire Basemap", "format": "tiles"}, {"files": ["NOMA    DS-HRRR-CONUS-3-KM-08-05-2016_1600.json", "NOMADS-HRRR-CONUS-3-KM-08-05-2016_2000.json", "NOMADS-HRRR-CONUS-3-KM-08-05-2016_1400.json", "NOMADS-HRR    R-CONUS-3-KM-08-05-2016_1800.json", "NOMADS-HRRR-CONUS-3-KM-08-05-2016_1500.json", "NOMADS-HRRR-CONUS-3-KM-08-05-2016_1900.json", "NOMADS-HRRR-CONU    S-3-KM-08-05-2016_2100.json", "NOMADS-HRRR-CONUS-3-KM-08-05-2016_1700.json", "NOMADS-HRRR-CONUS-3-KM-08-05-2016_1200.json", "NOMADS-HRRR-CONUS-3-KM    -08-05-2016_1300.json"], "package": "", "type": "vector", "name": "Weather Json Vectors", "format": "json"}, {"files": ["dem_08-05-2016_2100_27m.js    on", "dem_08-05-2016_1500_27m.json", "dem_08-05-2016_1800_27m.json", "dem_08-05-2016_1900_27m.json", "dem_08-05-2016_1300_27m.json", "dem_08-05-201    6_1600_27m.json", "dem_08-05-2016_1400_27m.json", "dem_08-05-2016_1700_27m.json", "dem_08-05-2016_1200_27m.json", "dem_08-05-2016_2000_27m.json"],     "package": "", "type": "vector", "name": "WindNinja Json Vectors", "format": "json"}]}, "input": {"domain": {"xmin": -112.03239440917967, "ymin": 3    3.53524211753991, "ymax": 33.56785995265315, "xmax": -111.99068069458008}, "products": "vector:true;raster:true;topofire:true;geopdf:false;weather:    true", "parameters": "forecast_duration:8;vegetation:grass;mesh_choice:fine", "forecast": "NOMADS-HRRR-CONUS-3-KM"}, "email": ""}

topofire.zip: 505365
tiles.zip: 1094648

**Comment by fspataro** [comment]
Are those file sizes in B, KB, MB? 

The point six files are 
topofire.zip = 686KB
tiles.zip = 711KB

**Comment by nwagenbrenner** [comment]
B's

**Comment by fspataro** [comment]
Thanks, makes sense so these are very close to the point six test run:

topofire.zip = .5MB vs .6MB
tiles.zip = 1.1MB vs 0.7MB

So it's not a "large" download...

I'll upgrade our iPad to 9.3.3 as see if it experiences the same issue.

**Comment by fspataro** [comment]
I updated our older iPad to 9.3.4 (just released).  

- Point six sample job downloads fine.
- Create a new job around roaring lion.  Probably 10mi x 10mi for 12 hours using the CONUS short term.
  - job time about 8 minutes
  - download status bar display 45 outputs to download.  Not sure where that number comes from.
  - the download progressed normally from 1 to 30.  At 30 it "hung" up for about 30-45 seconds then jumped directly to the "download complete" message.  It did seem like something was wrong during that time frame.
  - once the download completed display seemed normal  

In the end I don't think anything was "wrong" with the download, but potentially something is off with the progress dialog? And maybe during the download of the larger zip file, something is amiss with the dialog refresh or event/window messaging. 

I also had very little running at the time of the test, so potentially if there were other apps running this might be more problematic.

**Comment by CorbyHarkonnen** [comment]
so just a quick note on this one. some of the files are being downloaded synchronously, thus causing the app to 'freeze'. I added a note to the download dialog for the time being so people don't get confused and close the app thinking it is actually hung.

**Comment by CorbyHarkonnen** [comment]
with v1.0.4 we've started zipping up all outputs for transport, so now there is less of a change that the app will 'freeze' when downloading.

file sizes are smaller, and there are now a max of 5 files to download (assuming ALL outputs are generated), but generally there will be 3 (weather, TopoFire, clustered)

**Comment by CorbyHarkonnen** [comment]
have there been any updates from the user on this one since the changes? can this be closed out?
