### ISSUE TITLE
Simulations are very slow on the server

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#13]
I'm not sure why, but when I start a simulation from my phone it takes a very long time before I can download it from the server.  Currently I've been waiting 20 minutes for a simulation and it's still not done.  The actual WindNinja on the server should be much faster than that I think.  I'm wondering where the long waits are coming from?  Is it Zack's server fetching the offline topo?  Is the GCS server just being used for other things?  I realize that the GCS server we're using is just for testing...  and if the problem is the server is being used for other things that's fine.  Just want to be sure there isn't some other bottleneck we should be concerned about.

**Comment by fspataro** [comment]
Just to clarify: the server-side "job" does three things:

1. Runs windninja (which includes clipping the dem, downloading forecasts, running the cli, converting formats)
2. Grabs topo tiles from Zack's server
3. Generates raster tiles.  This step is the most time/cpu intensive.  

This job created 15 iterations... so 15 tilesets are being created.  I'll have to look and see how mapnik load is being distributed.  

This a development server being used for other things.

**Comment by jforthofer** [comment]
OK, thanks for the clarification Fred.  So the slowest part is the generation of raster tiles...  I wonder how much speed up there would be if no tiling was done?  I go back and forth as to the benefit of having coarser/finer vectors displayed depending on the zoom level.  On one hand, it's nice to be able to see something when you're zoomed way out, but on the other hand, are these coarse vectors very useful to our users?  Maybe not...

**Comment by fspataro** [comment]
The option is to create one large image/raster without tiles.  

Pros: 
Faster server side processing
No tile edge/arrow issues

Cons:
Most "zoomed" out scales will be a blur of color 
Phone app may have a hard time with size of image since it has to now load the whole image into the map to see any one portion. --- I think we verified this already with an image that's same size as all the tiles at zoom level 16 but will retry.  Maybe there's an optimal image size

**Comment by fspataro** [comment]
More details on the run from above:

15 iterations
extent 24KM x 30KM (ish)
20K points generated for each result
Level 16 requires 4524 tiles (78 x 58) That's probably not realistic if this is common extent size.
Level 16 full resolution image would be 19K x 14K
The total tileset of a single iteration is 6300ish files and 10MB

**Comment by jforthofer** [comment]
OK, so maybe we found a problem with the raster method?   I think this extent is reasonable for a user to try...
By the way, WindNinja mobile on my phone tells me "Failed" when I check the run status now.

**Comment by CorbyHarkonnen** [comment]
"2015-05-08T13:14:09.770000-06:00 | ERROR | Files count would require ZIP64 extensions"
looks like there were too many raster tiles for the current zip method to handle.

**Comment by jforthofer** [comment]
Everything seems to be fast on the server now, closing this ticket...
