### ISSUE TITLE
continued registration emails even when registration executed "successfully"

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#130]
Dan Jimenez reported this problem on his Samsung S5 phone.  He keeps getting emails to confirm registration, even after he successfully registers, or at least the server tells him successfully registered.

**Comment by fspataro** [comment]
When does he get these emails? Every time he opens the app? 
What does his account record on the server say his status is?

**Comment by nwagenbrenner** [comment]
His status say "accepted" and he's able to use the app, he just keeps getting the emails. I think originally he missed the 10-min window to follow the link and complete the registration, so had to be sent a second link. Perhaps the recurring email issue is related to that?

**Comment by fspataro** [comment]
i'll look at the code but it shouldn't be "looping" and sending more than one, unless he keeps clicking on the register email and it's an "old" one.  So tell him to stop clicking on the link if he's registered.  Otherwise it might be something with the email server?

**Comment by fspataro** [comment]
Do we need to look into this any more?

**Comment by jforthofer** [comment]
I think it can probably be closed, hopefully your change earlier fixed it, if it pops up again we can reopen.
