### ISSUE TITLE
Can't plot output without closing and re-opening the app

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#131]
Happens on my phone (SM-G930V, Android 6.0.1) and Jason's (same phone). The run appears to download properly, but when you click plot nothing happens. If you navigate away from the app and then back again the vectors plot normally.

**Comment by nwagenbrenner** [comment]
Other users are reporting this issue now as well. It seems this is likely related to the latest system update. My system was updated on Sep 8.

**Comment by jforthofer** [comment]
We should consider sending out an email to all users letting them know about this problem and the workaround.

**Comment by fspataro** [comment]
This is definitely one of the major challenges with having a mobile application.  The base OS is updating on a very frequent time-frame (and it gets deployed to devices in an erratic manner --- my phone is still 5.1 and was a first gen, newly released phone when I got it last summer).

**Comment by CorbyHarkonnen** [comment]
moved to using jquery ajax call do download json files as the filetransfer plugin was downloading out of sync of the rest of the app, causing the download window to end prematurely and 'Plot' button to be enabled before the run was fully initialized

**Comment by jforthofer** [comment]
This seems to be fixed on my phone, thanks Tory.
