### ISSUE TITLE
MODIS data isn't plotting

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#135]
It looks like there is a problem with the MODIS data? The VIIRS data looks good.

**Comment by CorbyHarkonnen** [comment]
I didn't touch the MODIS data urls, is it possible they just don't have any data for this year yet?

the layers I'm using are 'Last 24 hour fire detection', 'last 12 hour fire detection', and 'Current Large Incidents'

**Comment by CorbyHarkonnen** [comment]
found it. looks like they changed the URL for the active fire maps services. will update with new URL

**Comment by nwagenbrenner** [comment]
The MODIS data is showing up now.
