### ISSUE TITLE
Submitted/Updated times not reported in the same time zone

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#136]
The Submitted/Updated times in the "Runs" tab are not consistently reported in the same time zone. Initially they are the same (server time in UTC), but at some point they get out of sync (at least sometimes) and one will be in UTC and the other in local time (based on the phone's location).

**Comment by CorbyHarkonnen** [comment]
I think this is fixed for the most part - everything _should_ be displaying in MST/MDT. I am going to be adding in moment.js in the next build which will allow much greater control over date/time display & manipulation. But this does bring into question: what timezone do we want to display times in? all the run data is in MST/MDT (since that's what the server is set to), but with moment.js I can convert the dates/times into any timezone we want. the only caveat is that detecting the user's timezone may not give us the 'correct' timezone - browser timezone autodetect can be flaky, so I'd recommend either leaving everything in Mountain time, or converting to GMT. Thoughts?

**Comment by nwagenbrenner** [comment]
I think the time should be reported in the time zone of center of the DEM. Seems like that would be most intuitive for the user.

**Comment by fspataro** [comment]
Question:  What are the time values reported on an WindNinja CLI output files? I think i'm using the auto-detect parameter in the CLI.  Are these data time stamps - server time or time for the extent of the run?

**Comment by nwagenbrenner** [comment]
Actually, you're right, UTC should be fine for the submitted/updated times (but we should indicate UTC in the time stamp). Simulation time steps should be in the local time zone for the DEM though.

**Comment by nwagenbrenner** [comment]
WindNinja reports times in the local time zone (the time zone of the DEM).

**Comment by CorbyHarkonnen** [comment]
ok. if WindNinja reports the 'local' time zone from the DEM, then that should be what get's displayed in the app (in all locations - I use the same formatting function everywhere). Once I get moment.js added to the project. I can control this a little better.

the Submitted and Updated times in the run list come from the job.json messages - I think those are pulled from the server time -Fred, can you confirm?

as for the dates/times displayed for the simulation run, those are pulled from the file names (though, they have no timezone info currently, so we'd have to add that data somehow (either by modifying the fine name convention, or sending the timezone data back in the job.json file)

**Comment by fspataro** [comment]
Correct API date/times ie in the messages section of the job json are server local time.  Result forecast date times are are WindNinja CLI generated which should be DEM center local time.  For the next server-side update I'll try to configure all of those to UTC or time-zone attributed so we can display as needed.

**Comment by CorbyHarkonnen** [comment]
ok, with 1.0.4 we have proper timezone info for runs. 

Currently, I am displaying everything in UTC/GMT time (hard-coded). Did we want to allow users to be able to pick what timezone dates/times are displayed in? this would require adding a drop-down list in the options menu, and a new config file item (fairly simple, would just need input as to which timezones to include)

see [List of tz database time zones - Wikipedia](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) -- TZ field in chart

I would assume everything in the U.S. (including Alaska) and GMT, thoughts?

**Comment by nwagenbrenner** [comment]
Fixed.
