### ISSUE TITLE
Client-side registration status (sometimes) doesn't update when a new user is approved

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#139]
We just ran into this issue today (and I think this has happened before). A new user completed the registration process, but the app kept telling him his registration was pending. I confirmed that the registration is "accepted" on the server. The user was going to try completely exiting and re-launching the app. I haven't heard yet whether that was successful. In any case, the update should be detected instantly, right? Is the app caching the status or something? The user was on an iPhone. I can provide other details if needed.

**Comment by CorbyHarkonnen** [comment]
It is totally possible that the result is being cached, closing the app completely should fix this, and I can add the no-cache option to the request(s), but depending on where the build team is on the current version, the code fix might not make it in until next version

**Comment by jforthofer** [comment]
I can confirm that when the user closed out of the app and restarted, the registration was detected as accepted and they could do wind runs.

**Comment by CorbyHarkonnen** [comment]
issue fixed in android version 1.0.3. iOS fix is in the code, but waiting for next build as to not delay pushing of version 1.0.3 to app stores

**Comment by CorbyHarkonnen** [comment]
issue should have been fixed in v1.0.3 (in stores). Closing
