### ISSUE TITLE
Hide legend and time slider button unless run is loaded in map

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#14]
Currently, the wind speed legend and time slider are always visible on the map. These probably shouldn't appear until a run is added to the map.

**Comment by jforthofer** [comment]
Good idea...  it's unclear what they do if a simulation isn't loaded.

**Comment by jforthofer** [comment]
Oops... accidentally close this, reopening...

**Comment by fspataro** [comment]
Not following this one exactly... the buttons on the bottom left turn the legend and slider on/off.  You want to make it so they can't turn them on until a run is loaded? Or you can't turn them off?

**Comment by nwagenbrenner** [comment]
I think those icons should not be visible until a run is added to the map. If that's possible. Just because they have no purpose until there is run information to view.

**Comment by fspataro** [comment]
Gotcha!  Changed the title a little
