### ISSUE TITLE
GeoMac layer is broken

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#141]
Nothing plots when GeoMac is turned on. Not sure if this is a problem in the app or with GeoMac.

**Comment by CorbyHarkonnen** [comment]
it looks like they changed the URL of the service. easy fix, but it does require a rebuild and publish to the store(s)

**Comment by nwagenbrenner** [comment]
Okay, let's just get it into the next release.

**Comment by CorbyHarkonnen** [comment]
it looks like they also removed the ability to use a layer by its name, its back to indexes only

**Comment by CorbyHarkonnen** [comment]
fix is in v1.0.4
