### ISSUE TITLE
Back button doesn't work as expected

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#143]
If you open one of the side menus (for example the "Runs" menu or the "WindNinja Mobile Settings" menu) and then push the back button (the built in back button on Android), it apparently closes the app.  The expected behavior would be to exit the menu.

**Comment by CorbyHarkonnen** [comment]
fix is in 1.0.4

**Comment by fspataro** [comment]
Fixed for 1.1.2.  I also added the standard close button in the top right corner of the About, Feedback and Help popups.
