### ISSUE TITLE
Get rid of the weather model choice

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#147]
We should just use HRRR for CONUS and NOMADS-HIRES-AK for AK. This will make the interface even simpler for new users.

**Comment by fspataro** [comment]
Options:

1. No selection or display to user, server determines model 
-- remove choice from UI (maybe static text saying 'HRRR for CONUS or NOMADS-HIRES-AK' for Alaska)
-- don't send value to server, 
-- server decides appropriate value

2. No selection for user, app determines model 
-- remove choice from UI but display which model is going to be used
-- app determines model from domain extent
-- app sends value to server as currently implemented
-- server processes as currently implemented

I probably prefer #2 if we can query the domain-model association in the phone... which should be possible if we keep the geometry pretty simple.  It also allow for flexibility for "advanced settings" later down the line that would allow the user to select a choice

**Comment by fspataro** [comment]
Server now has a "forecast=auto" mode.  Two polygon boundaries are created for AK & CONUS.  The WKB for the geometry is part of the config file.  

When forecast=auto, the domain extent will be checked against any boundary polygons in the 'AUTO_FORECAST' section of the config and return the first that intersects.  

The server will still except a specific forecast value for other uses or 'advanced settings' functionality.

**Comment by fspataro** [comment]
server-side complete and passing tests

**Comment by CorbyHarkonnen** [comment]
app side updated and ready for testing
