### ISSUE TITLE
Offline topofire tiles not being sent to phone

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#149]
It looks like these tiles aren't being sent to the phone in version 1.1.1. I don't see any topofire tiles in the job directory on the server and when you click on the offline basemap nothing is displayed.

**Comment by fspataro** [comment]
Fixed for 1.1.2

Flag for topo to be generated was sent to false for some debugging, forgot to reset it.  You can see this in the job.json file 
input\products\topofire=false
