### ISSUE TITLE
Zoom to simulation extents button

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#15]
It would be good I think to add a button (when a simulation is loaded) that will zoom back to the outer extents of the simulation.  This would help in case the user accidentally zooms or pans too far and gets "lost".

**Comment by CorbyHarkonnen** [comment]
added button to zoom back to run extents

**Comment by nwagenbrenner** [comment]
It looks like this button is gone now? Also, it's not clear what the 'zoom to run' button does in the Runs and Display tab.

**Comment by CorbyHarkonnen** [comment]
button is there, renamed from 'Zoom to run' to 'Zoom to simulation extents'

**Comment by nwagenbrenner** [comment]
The button doesn't work (it doesn't seem to do anything). Also, I thought there used to be an icon that did this in the map view (rather than in the Runs tab).
