### ISSUE TITLE
Help tab isn't scrollable

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#151]
The text in the Help tab doesn't fit on one page, but you can't scroll to continue reading. This also means you can't exit the Help tab without closing the app because the "Got it" button you have to click to close the Help tab is at the bottom. The "back button" does not close the Help tab. I did figure out that you can scroll to the end by tapping the page, although, this isn't intuitive behavior (and you can't tap to get back to the top of the text). Ideally, the tab should scroll and the "back button" should exit the tab.

**Comment by fspataro** [comment]
Fixed for 1.1.2

Removed the 'Got It' for the standard X close button at the top.  The back button will also correctly close this.  Pragmatically setting the size of the popup and internal content div so that scroll works correctly.
