### ISSUE TITLE
Job remaining in "new" state if wrapper fails to start

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#154]
This is mostly a testing/setup issue to be aware of:

Using the deploy script with the "app" keyword will wipe out the windninjawrapper.config.yaml file so you need to deploy both "app" and "config".  

The wrapper script is likely failing in the import stage when launch by the queue manager.  Can we capture and log this failure to the job result?  The error should be logged in the supervisor log.

**Comment by nwagenbrenner** [comment]
Should be fixed in the new server deployment work.
