### ISSUE TITLE
Run fails after the momentum solver completes successfully

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#156]
The run fails after the outputs are written. This is job 418a2319d9ae49d0ade57a039562b8c1 on the dev server. I was watching as the WindNinja run completed and the outputs were being written to wncli/output. Then, when the runs were done it looked like the output folder was deleted and a new folder called "results" was created, but there is nothing in it. Is there some issue moving the outputs around? @fspataro 

Log file attached:

[windninja.log](https://github.com/firelab/windninja-mobile/files/2942070/windninja.log)

related issue #133

**Comment by fspataro** [comment]
I'm jumping on the server to take a look ... the log says:

WindNinjaCLI did not produce windninja ascii outputs for the job parameters

I'm also noticing that the stdout for the solver doesn't include the "Time" lines.  The code after the CLI is really dependent on the output of the date time stamp.   If the momentum solver generates results in a completely different manner than the basic solver, we'll have to generate a new pipeline for processing the results.

**Comment by fspataro** [comment]
The job cli looks like it's creating all the outputs correctly and the error boils down to that missing line in the stdout.  This is definitely a pretty fragile implementation but it was the only place to get the info.  The core windninja parts are heavily biased to a "desktop client" where the user would already know this info.  In the client-server architecture were the server, client and domain can all be in 3 different timezones, some way to get at this info explicitly would be helpful.  

The other option is for the job processor to figure out all that info but it added a bunch of extra processing that was duplicated in the core WindNinja so we relied on stdout for the info. 

![image](https://user-images.githubusercontent.com/5933821/53975456-1b750e00-40c2-11e9-9818-d77533cb6025.png)

How hard is it to get that line into the stdout when the momentum solver is running? 

It would take a good day to rework and test the processing pipeline to handle the missing metadata.  But then we'd be re-opening a number of client issues re: the time zone info in the app.

**Comment by nwagenbrenner** [comment]
Just added the simulation time output to the momentum solver stdout. I re-built and re-installed WindNinja. Looks like you edited some things on the server though (I see my foam path fix was commented out), so the runs are still failing. I think things should work now if you put them back the way they were.

**Comment by fspataro** [comment]
Great! 

I'm verifying the pre-commands can be set in the config file rather than in the py....

**Comment by fspataro** [comment]
woot woot... looks good.  I'm gettting "success" on that job with the pre-commands from the config file and the simulation time reads correctly.

**Comment by nwagenbrenner** [comment]
Sounds good. We'll do some testing to see what the job times are looking like.

**Comment by nwagenbrenner** [comment]
@fspataro Let's change the mesh_resolution to coarse while we're using the momentum solver. We can change it back to fine if we switch back to the other solver.

**Comment by fspataro** [comment]
@nwagenbrenner right now we have the mesh_resolution as an option to the job api and the mobile app is setting hard coded value.  I'll start a new issue so @CorbyHarkonnen can modify that in the phone.  Then default config setting will take over.

**Comment by nwagenbrenner** [comment]
Okay, this is a setting we definitely want to be able to set/change on the server (without having to do a new release). Ideally, all of the CLI arguments should be this way.

**Comment by fspataro** [comment]
just checked the code: we already migrated most of it out of the mobile app so it's good to go.  The client can still override some values if it wants but right now all the server side defaults will be used.  I'll configure the mesh to coarse.

**Comment by fspataro** [comment]
ok all setup now:
* momentum flag details (flag, mesh, etc) are configurable in yaml file and still overridable from job api
* openfoam pre-commands are configured in the yaml not the source code.
