### ISSUE TITLE
Raster max speed error.

### ISSUE THREAD

**Issue by JoseluDAM2000** [firelab/windninja-mobile#159]
In this simulation, the max speed from the raster was 79. 
Thats correct? 
Are milles per hour?

http://windninja2.wfmrda.com/api/job/c5c29066-33ce-4e7e-bd53-83fe52bae01c

**Comment by fspataro** [comment]
the max speed values are inclusive of the weather data as well as the simulation data if the product weather:true.  The mobile app display both the simulation arrows and the weather so this value was provided to account for both.   If you're not using the weather data then set that value to false and the max values should be limited to just the simulation data.  If you're using both. you'll need to calculate the individual values manually.

**Comment by fspataro** [comment]
sorry, the max speed for each sub dataset is also provided.  It does look like the max of 79 mph is from the simulation result.  You can find it in this file: 

http://windninja2.wfmrda.com/output/c5c2906633ce4e7ebd5383fe52bae01c/20190319T0500.json

We'd need to one of the windninja devs to take a look at that specifically to see if there was something wrong but "job system" is correctly summarizing the results.

**Comment by fspataro** [comment]
Do we need to research this more or can we close it?

**Comment by JoseluDAM2000** [comment]
For my part, everything is correct. If the server already calculates these values ​​correctly, the issue can be closed without problems.

**Comment by fspataro** [comment]
Thanks @JoseluDAM2000 

I'll close it for now.
