### ISSUE TITLE
Error on registration

### ISSUE THREAD

**Issue by JoseluDAM2000** [firelab/windninja-mobile#161]
When I try to register, the server responds with this:
`{'message':'argument of type 'NoneType' is not iterable'}`

**Comment by fspataro** [comment]
Can you post the request data? Seems like something is incorrect in there...

**Comment by JoseluDAM2000** [comment]
`{`
     `"deviceId":"6d8c50696f07eb6c2f20736891b288ec",`
     `"email":"Jramireztsyl@gmail.com",`
     `"model":"MS-7817",`
     `"name":"Joaquin Ramirez",`
     `"platform":"Windows",`
     `"version":"8.1"`
`}`

**Comment by fspataro** [comment]
confirmed that is the correct json package.  the error is occurring for my tests as well.  I think the account data store is read-only. 

@nwagenbrenner reading folder permissions on linux is not best skill, can you confirm the folder has write access for the web process?

**Comment by nwagenbrenner** [comment]
The account folder has write permissions. We've been able to create new accounts via the latest test build from GCS, so it seems like it's not a permissions issue.

**Comment by fspataro** [comment]
thanks... we're all of your new accounts "auto register"?  might be something with the register verify email.  I did have a typo check in when i removed the time window, maybe that didn't get sync correctly. I'll check that.

**Comment by fspataro** [comment]
ok, i found the error... an empty list in the yaml file turns into NoneType in the config class rather than [] and then it throws an iteration error.  Fixed on the server. 

please verify and close

**Comment by JoseluDAM2000** [comment]
It's working perfectly now.
