### ISSUE TITLE
Unnable to simulate sometimes

### ISSUE THREAD

**Issue by JoseluDAM2000** [firelab/windninja-mobile#164]
![imagen](https://user-images.githubusercontent.com/22506382/58866118-3141a180-86b8-11e9-962b-3a788eb075c3.png)

**Comment by fspataro** [comment]
@JoseluDAM2000 are you able to reproduce this or notice any consistency to the bad results?  

If you attach a postman file , i'll try to repo

Couple of things:

1. The "Job name is required" error comes directly from the parameters validation of the flask framework api/controller.  This validation runs before the windninja custom code kicks in.  This would indicate a request formatting or network related error rather than an issue with the job creation/proccessing code. 

2. The POST request for job is a little non-standard from a typical REST request these days.  The values are supposed to be in the URL parameters not a JSON body. I'm sort of surprised the JSON body even works, so it's possible the validation task is not able to parse the JSON body correctly.  Your postman would look like this:

![image](https://user-images.githubusercontent.com/5933821/59624315-ac14ae80-90f3-11e9-9de3-062a8b4d81e4.png)

**Comment by JoseluDAM2000** [comment]
Can you check if there is any problem?
It's too difficult to you change the request to work as a standard POST request?

The app that i sent you the last time use that format to send the simulations to the server.

[WindNinja error.postman_collection.zip](https://github.com/firelab/windninja-mobile/files/3334616/WindNinja.error.postman_collection.zip)

**Comment by JoseluDAM2000** [comment]
Today while testing the application, we have noticed a "pattern" in the errors.

At some point, a simulation fails, and from then on, the request to simulate seems not to return what it should, but the server sends the emails at the end of those simulations.

![imagen](https://user-images.githubusercontent.com/22506382/60439847-d1390f00-9c13-11e9-94df-fd6ee154a40a.png)

**Comment by fspataro** [comment]
hi @JoseluDAM2000 

Below is the list of jobs from around that time frame with status from the server.  I see a few failures but the ones in your list that say "succeeded" are showing succeeded on the server.  I don't know what this UI is or what "Not Ok" means in that case.  Maybe this UI has an issue after a failure is found. 

742a6551192e4d34907828cac0a5e275 | dfernandez_001 | succeeded |
fb8b477c07f6440590d5c54335842918 | Abcd2 | succeeded |
e79933abf6a341c095bceb8092c65774 | Abcd2 | succeeded |
9fa164fd8b504db0b990d326203f3fda | Abcd2 | succeeded |
1e5c2d592dcc48ebadc3af5c1d2c89f6 | TEST_ZERO | failed | Job domain is outside the supported auto forecast bounds
f7e8f40a09c0486287675aafaa3b2675 | Abcd | succeeded |
8fc6dbffd1df407fb4f5f3f315a3f30b | GAtest03 | failed |  Failed to download file. & FOAM FATAL ERROR: bad size -2147483647
5396114b132542a1bbac58410104de94 | Yxhxyxy | succeeded |
7913c9c109204c11ba707fa8c196c5df | TestGA02 | succeeded |
26fbbb9207aa4e059f675efa4dad8792 | GAtest02 | succeeded |
838b69c0a8dc4a0ca1c8b8e02b1206f9 | Aaaa | failed | Failed to download file. & FOAM FATAL ERROR: bad size -2147483647
5bd20163393d42ef887b56ba8fbeac96 | TestGA01 | succeeded |
23ad3730b60a426592a253d9fed528c2 | Test hdiaz | succeeded |
7be13dce44da432c86eb42a4f15fb910 | Testnat3 | succeeded |

**Comment by fspataro** [comment]
for example in the above UI picture it says Yxhxyxy is status "succeeded" but has 'Not Ok'... what does this mean? 

The job status is 'succeeded' and output were generated, email was sent etc... 
http://windninja2.wfmrda.com/api/job/5396114b132542a1bbac58410104de94

You can download the tile zip here... i see image files with arrows...not sure what else would be wrong
http://windninja2.wfmrda.com/output/5396114b132542a1bbac58410104de94/tiles.zip

**Comment by fspataro** [comment]
attached are the logs for the two above that fail with the download/openfoam issue. Both seem to be the same, forecast download fails then openfoam blows up.  @nwagenbrenner @jforthofer @ksshannon do you have any idea what this failure is about?

[windninja.8fc6dbffd1df407fb4f5f3f315a3f30b.log](https://github.com/firelab/windninja-mobile/files/3347116/windninja.8fc6dbffd1df407fb4f5f3f315a3f30b.log)
[windninja.838b69c0a8dc4a0ca1c8b8e02b1206f9.log](https://github.com/firelab/windninja-mobile/files/3347117/windninja.838b69c0a8dc4a0ca1c8b8e02b1206f9.log)



StdErr:ERROR 1: HTTP error code : 404
ERROR 1: Failed to download file.
Warning 1: Failed to download forecast, stepping back one forecast run time step.
ERROR 1: [blockMesh error] 

--> FOAM FATAL ERROR: 
bad size -2147483647

    From function List<T>::List(const label size)
    in file /home/ubuntu/src//OpenFOAM-2.2.x/src/OpenFOAM/lnInclude/List.C at line 49.

FOAM aborting

#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::error::abort() at ??:?
#2  Foam::lineDivide::lineDivide(Foam::curvedEdge const&, int, double) at ??:?
#3  Foam::blockDescriptor::setEdge(int, int, int, int) at ??:?
#4  Foam::blockDescriptor::makeBlockEdges() at ??:?
#5  Foam::blockDescriptor::blockDescriptor(Foam::Field<Foam::Vector<double> > const&, Foam::PtrList<Foam::curvedEdge> const&, Foam::Istream&) at ??:?
#6  Foam::block::block(Foam::Field<Foam::Vector<double> > const&, Foam::PtrList<Foam::curvedEdge> const&, Foam::Istream&) at ??:?
#7  Foam::blockMesh::createTopology(Foam::IOdictionary const&, Foam::word const&) at ??:?
#8  Foam::blockMesh::blockMesh(Foam::IOdictionary const&, Foam::word const&) at ??:?
#9  
 at ??:?
#10  __libc_start_main in "/lib/x86_64-linux-gnu/libc.so.6"
#11  
 at ??:?
ERROR 1: [decomposePar error] 

--> FOAM FATAL ERROR: 
Cannot find file "points" in directory "polyMesh" in times 0 down to constant

    From function Time::findInstance(const fileName&, const word&, const IOobject::readOption, const word&)
    in file db/Time/findInstance.C at line 203.

FOAM exiting

Segmentation fault (core dumped)

2019-07-01 12:37:37,056	ERROR	model.py	ERROR 1: HTTP error code : 404
ERROR 1: Failed to download file.
Warning 1: Failed to download forecast, stepping back one forecast run time step.
ERROR 1: [blockMesh error] 

--> FOAM FATAL ERROR: 
bad size -2147483647

    From function List<T>::List(const label size)
    in file /home/ubuntu/src//OpenFOAM-2.2.x/src/OpenFOAM/lnInclude/List.C at line 49.

FOAM aborting

#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::error::abort() at ??:?
#2  Foam::lineDivide::lineDivide(Foam::curvedEdge const&, int, double) at ??:?
#3  Foam::blockDescriptor::setEdge(int, int, int, int) at ??:?
#4  Foam::blockDescriptor::makeBlockEdges() at ??:?
#5  Foam::blockDescriptor::blockDescriptor(Foam::Field<Foam::Vector<double> > const&, Foam::PtrList<Foam::curvedEdge> const&, Foam::Istream&) at ??:?
#6  Foam::block::block(Foam::Field<Foam::Vector<double> > const&, Foam::PtrList<Foam::curvedEdge> const&, Foam::Istream&) at ??:?
#7  Foam::blockMesh::createTopology(Foam::IOdictionary const&, Foam::word const&) at ??:?
#8  Foam::blockMesh::blockMesh(Foam::IOdictionary const&, Foam::word const&) at ??:?
#9  
 at ??:?
#10  __libc_start_main in "/lib/x86_64-linux-gnu/libc.so.6"
#11  
 at ??:?
ERROR 1: [decomposePar error] 

--> FOAM FATAL ERROR: 
Cannot find file "points" in directory "polyMesh" in times 0 down to constant

    From function Time::findInstance(const fileName&, const word&, const IOobject::readOption, const word&)
    in file db/Time/findInstance.C at line 203.

FOAM exiting

Segmentation fault (core dumped)

**Comment by nwagenbrenner** [comment]
I only looked at 838b69c0a8dc4a0ca1c8b8e02b1206f9, but the wx forecast downloaded (sometimes it takes a few tries which is what the "failed to download/stepping back one timestep" messages are about. You can see the downloaded forecasts in wncli/NOMADS-HRRR-CONUS-3-KM-dem.tif/20190701T1100/20190701T1100.zip. 

Bad values (the negative numbers below) were written to the file (blockMeshDict) that controls blockMesh, which is why OpenFOAM is failing (the mesh isn't being generated).

    blocks
    (
      hex (0 1 2 3 4 5 6 7) (-2147483648 -2147483648 -2147483648) simpleGrading (1.0 1.0 1)
    );

I'm not immediately sure how that could happen. I've never seen that before. I'll download the case and look a little closer.

**Comment by nwagenbrenner** [comment]
There is a problem with the DEM, it only has one column. 

![dem](https://user-images.githubusercontent.com/3696653/60466781-de54fe80-9c11-11e9-81e8-c0d8cfb49f56.png)

**Comment by nwagenbrenner** [comment]
I guess this is a check we could perform on the DEM in WindNinja before trying a simulation? For sure there has to be more than one row/column, probably more than 5 or 10 to do anything useful. @jforthofer @ksshannon

**Comment by nwagenbrenner** [comment]
And it's the same issue in 8fc6dbffd1df407fb4f5f3f315a3f30b. There is only one column in the DEM.

**Comment by ksshannon** [comment]
We can check it in the CLI when we check for no data values...

**Comment by jforthofer** [comment]
Seems like we should look upstream and determine why the DEM is just one column.  Was the domain specified actually like this, or is there some other problem causing it?  But yeah, it would be OK to do a check for greater than one column or row.

**Comment by nwagenbrenner** [comment]
It was specified that way: 

"domain": {"xmax": -101.86155012577156, "xmin": -101.8617750174939, "ymax": 35.17244470390325, "ymin": 35.1427232238655}

**Comment by jforthofer** [comment]
OK, yeah, some sort of a check on the "squareness" of the domain might make sense?

**Comment by JoseluDAM2000** [comment]
Hi @fspataro !

Those that are not Ok are simulations that have failed or the server, apparently, has not been able to return me. I have performed some tests and may be caused by the non-standard POST.

Is it too complex to change that request to be a standard POST?

**Comment by nwagenbrenner** [comment]
Fixed.
