### ISSUE TITLE
Don't display input wind vectors if show input wind = no

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#17]
It appears that the input wind vectors are displayed regardless of what 'show input wind' is set to. At least when the raster display type is used.

**Comment by CorbyHarkonnen** [comment]
this is 'technically' true. We're only creating one set of rasters (per forecast hour), so I create two layers using the same raster data and set the display limits of each one (max zoom of 10 for the actual run, min zoom of 10 for the input), so there is a level of overlap where the input will show regardless of if the option is on or not. The only solution to this would be to create two sets of rasters for each forecast hour (one set for just the run and one set for just the input), we decided against this as the raster generation is already the longest part of the run creation, and this would likely double the amount of time required to generate the rasters and package them for delivery.
