### ISSUE TITLE
Issues with the 'Layers' box 

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#18]
When the page is first loaded, the drop down menu under 'Layers' is blank. It should probably default to 'None.' Or maybe 'Wind' should be an option here and be the default layer that is added to the map. Also, there are currently three options in this drop down menu: None, GeoMac, and MODIS. It lets you check all three, so if None is checked, but GeoMac is also checked, the GeoMac layer is shown.

**Comment by CorbyHarkonnen** [comment]
Updated Layers drop-down to have a title and removed 'none' option
