### ISSUE TITLE
Cleanup arrows at edge of mapnik tiles

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#20]
Arrows that cross the edge of tiles do not align and look sloppy.  

Possible solution: try using "vector arrows" over "icons".

**Comment by nwagenbrenner** [comment]
This seems to have been fixed. Can we get rid of the vector option and just have the icons raster? I think this is what we agreed on in the last meeting, right?

**Comment by CorbyHarkonnen** [comment]
yeah, I'll be removing the 'Vector' option probably with the next build. there's a couple of other items attached to this functionality and I didn't want to break it all just yet.

**Comment by CorbyHarkonnen** [comment]
removed display type option from display and defaulting to using Raster output.
