### ISSUE TITLE
Unable to download results

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#21]
This appears to be specific to Jason's phone... will try to test/debug during meeting

**Comment by nwagenbrenner** [comment]
I'm not able to download results without wireless. I have decent cell coverage, but the results never download. The dialog box pops up and says the files are being downloaded and the output progress bar moves as if files are being downloaded. The dialog box eventually closes and when I click run status it says the files have been downloaded. But the display type options (raster/vector, add run to map) are still grayed out.

**Comment by CorbyHarkonnen** [comment]
this was an issue with the logic being used when loading a run. re-wrote logic to not be dependent on Vector outputs, also fixed issue where short (1-hr) runs could not be added to the map.
