### ISSUE TITLE
Display type not respected when a run is first loaded 

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#23]
The default Display Type is set to raster, but Image Vector (clustered) is drawn no matter which option is chosen when the run is loaded for the first time. If the run is removed and then added back to the map, the appropriate Display Type is used.

**Comment by CorbyHarkonnen** [comment]
added code to reset the Display Type drop-down to 'Image Vector (Clustered)' when loading a run, this should guarantee that the drop-down matches what is getting added to the map by default
