### ISSUE TITLE
Input wind on/off not functional for raster output

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#24]
Some arrows in the raster format appear larger than others at the same zoom level. It looks like maybe the bigger arrows are the wx model arrows in the domain. We should allow the user to turn those on/off in the raster output.

**Comment by CorbyHarkonnen** [comment]
This was working previously, but it looks like there was a change to the way the raster tiles are being created. Working with Fred/Kegan to get rasters looking pretty again and have proper input display

**Comment by CorbyHarkonnen** [comment]
closing as we're generating vector weather now.
