### ISSUE TITLE
always show position on the map

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#29]
There is a new icon on the map that turns on/off the gps location on the map. Do we need this? My preference would be to just always have this on and get rid of the icon.

**Comment by jforthofer** [comment]
Natalie and I talked about this (after she wrote the above) and came up with a consensus on this (we were both a bit confused about what this was doing).  Let's leave this button and it's functionality, except:
1.  Could the buttons icon be changed to look the same as the actual icon on the map that shows your location (a cross-hair).
2.  When this button is pushed and the user is zoomed to their current location, could we keep the current zoom level, not the default zoom level?

**Comment by nwagenbrenner** [comment]
Also, if the gps icon is on and I pan away, so that the gps icon is no longer visible on the map, I would like to be able to click this button once to take me back to my location on the map. Currently, it just turns the icon off. So if the location icon is already not visible because you've panned away, it appears that nothing happened when you clicked the button. I have to click it twice to zoom back to my location. Should we just have the gps on all the time and use the button only to zoom back to the current location? If there is a need to turn the gps on/off maybe that should be a separate button. Right now, the behavior is confusing.
