### ISSUE TITLE
Need legend

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#3]
We need to come up with some sort of legend so the speeds can be read from the map.  One consideration will be how much of the screen they cover up.  Maybe it could be something the user opens and closes when needed, sort of like the "i" thing in the bottom right corner of the map.

**Comment by CorbyHarkonnen** [comment]
Quick question on the legend / wind arrows in general.

Is there a set 'interval' for wind speed we should be using (i.e. every 3 mph is an interval break.)
I currently am breaking down the wind speeds into 3 mph 'chunks' (e.g. 0-3, 3-6, 6-9, 9-12, 12-15, 15-18, 18+) to give us 7 arrow colors. does this work, or should I refine it/add more 'chunks'?

I've attached a screenshot of the legend as it sits currently for clarification.
![legend](https://cloud.githubusercontent.com/assets/10839029/6084986/3ba4e71a-adf3-11e4-9bf2-0fab71304d01.PNG)

**Comment by jforthofer** [comment]
We would prefer if the legend was dynamically generated to span the range from 0 to the max speed in the wind field.  This is how we do it in WindNinja for kmz.  The problem with a static one is that the ranges of speeds for different simulations might very greatly.  For example one simulation might range from 0-5 mph and another might range from 0-60 mph.
I attached an example legend we produce for kmz below.  One other thing we like is to just have 5 different colors, and specifically the ones shown below (blue, green, yellow, orange, red).
![legend](https://cloud.githubusercontent.com/assets/3695983/6085627/c7b0fa32-adf8-11e4-81a9-44062553614d.png)

If it's not possible to dynamically generate, let me know.  We'll figure out something that will work...  For example maybe we could have 3 different static legends we choose from depending on how strong the winds for the particular simulation.

**Comment by CorbyHarkonnen** [comment]
Dynamic should definitely be possible. I'll see what I can throw together with the 5 arrow colors

**Comment by jforthofer** [comment]
Great, thanks!

**Comment by CorbyHarkonnen** [comment]
![screenshot_2015-02-06-15-00-16](https://cloud.githubusercontent.com/assets/10839029/6088201/2e3e4c24-ae11-11e4-8c30-7f712ec0d180.png)

**Comment by jforthofer** [comment]
Looks great!
