### ISSUE TITLE
Legend text is cutoff

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#32]
"Wind Speed" is cutoff in the legend to "Wind Spe...", although it looks like it should fit. Also, can the order of vectors be changed so that the highest speeds are at the top and the lowest are at the bottom? This will be consistent with our kmz output.

**Comment by jforthofer** [comment]
It is not cut off on my phone...

**Comment by CorbyHarkonnen** [comment]
I upped the width of the legend, I believe it should show the full text properly now
