### ISSUE TITLE
pull-down notification bar doesn't work with the app

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#33]
Not sure if this is something you have control over, but I can't see my pull-down notification bar when the app is open. Also, the small bar at the top of the phone that is normally always visible (shows time, battery, notifications, etc.) is not visible when the app is open. The app takes up the entire screen. When I try to pull down the notification menu, the small bar appears with the time, etc., but the rest of the drop-down menu is hidden.

**Comment by CorbyHarkonnen** [comment]
Odd, the pulldown works fine on the phones in-house. but I can make it so the app does not run full screen (in fact, in iOS, you **can't** make it full screen, so this would make it appear the same across devices)

**Comment by nwagenbrenner** [comment]
Actually, Jason pointed out that if you pull down twice, it does work. Once gets you the small bar (the one that is usually visible), twice gets you the full pull down. This is different than how the drop down bar behaves in other apps, but we kind of like it. So maybe it's not a bug, but a feature.

**Comment by CorbyHarkonnen** [comment]
so, leave this as it is? (full-screen)

**Comment by nwagenbrenner** [comment]
Yeah, let's leave it full-screen.
