### ISSUE TITLE
multiple runs on the map

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#35]
Normally, when you select a new run, if there is already a run loaded on the map it is automatically removed so that only one run is visible at a time. I found an exception to this. If a run is loaded on the map and you use the pencil to select a new area and start another simulation, when you load that new run to the map, the old run is not automatically removed. So there are two runs visible on the map and it doesn't appear that there is a way to remove the old one.

**Comment by CorbyHarkonnen** [comment]
should now properly remove previous run from map when a new run is created/loaded
