### ISSUE TITLE
Modify text in settings

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#36]
When I modify the "WindNinja Mobile Settings" page, then hit "Save", the pop-up window says:

***Alert***
*Settings Saved.*

The "Alert" makes it seem a little like a problem occurred.  Could we remove the word "Alert"?

**Comment by jforthofer** [comment]
Same thing when I do the "Submit Feedback"...

**Comment by CorbyHarkonnen** [comment]
I can remove it (would look odd honestly), or I can replace it with some other title. For now I'll replace 'Alert' with 'Settings' and 'Feedback' respectively

**Comment by jforthofer** [comment]
Sounds good to me...
