### ISSUE TITLE
Run options

### ISSUE THREAD

**Issue by CorbyHarkonnen** [firelab/windninja-mobile#4]
I had some questions about the Run dialog. Currently. we have a slider for choosing the duration of the run from 1-72 hours in 1 hour increments (makes it somewhat tedious to use the slider in an effective manner), however I assume the 'valid' values are somewhat based on which model they decide to run:

e.g. UCAR-NAM-CONUS-12-KM is every 1 hour, so we allow from 1-X in 1 hour increments, 
but say NOMADS-GFS-GLOBAL-0.25-DEG is every 5 hours, so do we allow from 5-X in 5 hour increments? (just making up numbers here)

the other part of that is, what should a valid maximum time frame be (X), and is this again dependent on the interval of each model?

**Comment by jforthofer** [comment]
Yes, the valid values are dependent on which model is chosen.  I think we should try to keep this consistent with the regular WindNinja GUI, which is this:
The stride is always 1 hourly for all models.  The maximum duration is dependent on the model chosen.  You can find the duration for each model in the wx model tutorial here:
https://github.com/firelab/windninja/raw/master/doc/tutorials/WindNinja_tutorial4.pdf

Look at the table on page 5.
