### ISSUE TITLE
Alaska not working

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#41]
Seems to be a problem with Alaska domains. Run doesn't seem to download properly, even when the Alaska weather model is used.

**Comment by nwagenbrenner** [comment]
If the WindNinja run doesn't complete without errors, the app should notify the user that an error occurred during the simulation.

**Comment by nwagenbrenner** [comment]
Which DEM data source is the phone app using? I think lcp is the only option for most of AK since GMTED is down. Maybe this is the issue?

**Comment by fspataro** [comment]
We're currently using a local DEM on disk rather than going out to another remote server.  This DEM is CONUS only so Alaska simulations won't work.  I'll dig up the Alaska portion of the DEM and load it to the server.

**Comment by nwagenbrenner** [comment]
AK DEM is on AWS now.

**Comment by fspataro** [comment]
NOMADS forecast with 'dot' character in the name causes issues in a few places of the code.  Tried to clean it up on the server side by replacing the dot in the file names but forecast name in the client app causes another issue.  Making a new build

**Comment by fspataro** [comment]
Addressed in build 0.2.5

**Comment by jforthofer** [comment]
Looks good.
