### ISSUE TITLE
Notify the user that an error occurred during the simulation run

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#43]
Follow-up comment from testing in Alaska, but tracking as separate issue so it doesn't get lost.

**Comment by CorbyHarkonnen** [comment]
we should probably add this into the email/text notification, as the app itself doesn't do any polling against the server to check status (until you manually select 'Run Status' - which does alert the user to an error, just with very little information)

**Comment by nwagenbrenner** [comment]
Yeah, we should send this info in the email/text if those are requested, but we should also indicate that the run failed in the run status bar. Currently, there is no indication when WindNinja doesn't run successfully (e.g., for a failed AK simulation I just tested) -- run status says "Files ready to download." Instead, here we should say that an error occurred and maybe suggest that the user report the problem via the feedback section.

**Comment by CorbyHarkonnen** [comment]
This should be fixed as of 0.2.1, the button will now display 'Failed' as well as be disabled, and the user should receive a notification that the run has failed when checking status.

**Comment by nwagenbrenner** [comment]
Seems to be fixed.
