### ISSUE TITLE
Bug with "show coarse model" button

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#45]
If you view a wind simulation and turn on the "show coarse model" button, everything works as expected.  If you then load another simulation (without turning off the "show coarse model" button first), the newly loaded simulation will show on the map with the coarse model vectors off, but the "show coarse model" button is still turned on, which is incorrect.

**Comment by CorbyHarkonnen** [comment]
My bad, when I changed around the buttons, I must have forgotten to update the button status check in that portion of the code. will fix

**Comment by CorbyHarkonnen** [comment]
fixed
