### ISSUE TITLE
don't allow a run to be submitted without the area being selected

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#46]
If you click the pen, but don't actually draw anything, the app let's you submit a run anyway. There should be a check to ensure an area has been selected before the run can be submitted.

**Comment by CorbyHarkonnen** [comment]
There is some code that checks if the area is a point or 'null', but I haven't messed with that portion of code for a while, it may have broken in one of the last updates to the mapping API.
