### ISSUE TITLE
time slider bar is hard to navigate

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#47]
It's especially difficult when there are many time steps. Is it possible to add arrows at each end of the bar to move the slider back and forth one time step at a time?

**Comment by CorbyHarkonnen** [comment]
looking into a good way to simplify this

**Comment by jforthofer** [comment]
Will this be fixed or is there no easy fix?  Should it be left for a later version?

**Comment by fspataro** [comment]
There's not much else that can be done with slider.  We'll need to change the UI control to something else entirely.  We can pick it up again in the next phase.

**Comment by CorbyHarkonnen** [comment]
should be fixed in 1.0.3. see issues #138 & #99
