### ISSUE TITLE
feedback button

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#49]
Where does this info go? Can this information be sent to one of our windninja support email accounts? Let us know what you need.

Also can we change the name to "Submit Feedback/Questions"?

**Comment by CorbyHarkonnen** [comment]
this information is currently getting written to a file on the server (along with the registration data). Wouldn't be too hard to also add an email output to this (this would probably be done from within Fred's server API where the data gets sent)

changed the text of the button, will verify that it's not too long
