### ISSUE TITLE
Run parameters

### ISSUE THREAD

**Issue by CorbyHarkonnen** [firelab/windninja-mobile#5]
Looking for input on what run parameters users should have access to.

one idea so far:
Run name
Forecast Source
Forecast Duration

then an 'Advanced' button that opens up more options like: Vegetation, Mesh Size, Wind inputs/outputs (height and unit)

or have all the options available regardless and just default them to a 'standard' (e.g. vegetation: grass, mesh size: medium, wind input/output at 20.0 ft)

Thoughts, ideas? Thanks!

**Comment by jforthofer** [comment]
We think we want this to be very simple...  not a lot of choices to confuse people or clutter the screen.  More complex simulations can be done with the desktop version if needed.  We're thinking on the main sceen:
* **Run name**
* **Forecast Model**  The only choices here will be HRRR, NAM-CONUS, NAM-Alaska.  All of these are from the NOMADS server.
* **Forecast Duration** Valid choices depend on the model chosen.
* **Vegetation** Valid choices are grass, brush, and trees.


Items that are always set as constant (user doesn't see this):
"fine" resolution
20 ft output wind height
time zone automatically detected by WindNinja

**Comment by CorbyHarkonnen** [comment]
OK. I'll add the option for Vegetation and let Fred know that I'll be passing that value along to his service.

Thanks!
