### ISSUE TITLE
Modify layers

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#51]
Get rid of MODIS (GeoMac) (unless there is reason to keep this and MODIS since they are the same data) and add VIIRS (obtained from the same source as MODIS).

**Comment by CorbyHarkonnen** [comment]
I have attempted to add VIIRS to the layers, but it is in a completely different projection from everything else and I don't have the capability to re-project the data on the phone (and they don't allow re-projection on the server). If somebody is able to find a different source for the VIIRS data (or can support a 'call-through' re-projection), I can attempt to use that instead, but as of currently, it doesn't work.

**Comment by nwagenbrenner** [comment]
Let's just leave VIIRS out for now. And also get rid of MODIS (GeoMac) (since this is the same data as the MODIS option).
