### ISSUE TITLE
Text and layout changes

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#52]
Jason and I just went through all of the pages in the app and came up with a number of changes. I could try to describe them in a document, but maybe it's easier if I just meet with you guys in person to describe the changes? Let me know what you prefer.

**Comment by fspataro** [comment]
Go ahead and attach the document to this item.  I'll give it a quick review and decide if we need to have more specific items to track some of the changes or not.  Then we can have a discussion on the overall details.

**Comment by nwagenbrenner** [comment]
Here are the changes. Bold font indicates tab/window name. Italics are comments (not meant to be text in the app). Some things were hard to describe, so we may need to talk in person about some things. We also weren't sure how difficult some of the changes would be to implement, so this is all up for discussion.

[windninja_mobile.docx](https://github.com/firelab/windninja-mobile/files/19587/windninja_mobile.docx)

**Comment by fspataro** [comment]
First look thru... most seem reasonable, although I wish we had handled some of the structural design earlier as it gets more complicated to adjust at this point but it's not too drastic at this point.  

The only item that I'd push back on is having multiple emails - one for registration and one for alerts.  I can't come up with a really good reason for this situation since we don't allow access to runs from other devices at this point.  The email for registration should be accessible on the device.  More emails just adds more complication and probably would be the weak point to some sort of registration spoofing. 

I'm going to break the document into issue items so we can discuss and work on them individually.

**Comment by nwagenbrenner** [comment]
Sorry we didn't figure out these layout changes earlier. Until now, there were just more pressing issues to work through. These layout changes are all things Jason and I think would be good, but if something on the list seems not doable at this point, then we can consider saving it for future work.

One reason for allowing multiple emails is that a user may register with one email address (e.g., someone.fs.fed.gov), but want/need alerts to go to another email address (i.e., a personal one that can be checked remotely...there are strange/prohibitive issues with checking/forwarding FS mail). We want FS users to register with their FS accounts, but it may not always be convenient for them to access that account on their mobile device. Eventually we would want to allow multiple devices per user. In our 'management database' we can keep track of users by associating their device ID(s) with their registration email, but allow use of an alternate email for alerts. 

Having said all that, I suppose it's not crucial that we allow for all of this right now. This just came up because we were trying to figure out how to simplify/clarify the setup and start-up pages.

**Comment by fspataro** [comment]
Ok, makes sense... the 'management database' is definitely the issue right now as it wasn't apparent early on that we pushing in that direction in this SOW .... I'll figure something out that's a good compromise of functionality without building out a full blown database system.

**Comment by nwagenbrenner** [comment]
Sounds good. Yeah, I don't think we really knew how we would handle the security side of things when we started this work. We are still figuring this out and I think as long as we have the needed pieces exposed (e.g., asking for and storing the info we need from the phone), this is work that can be expanded on in the future.

**Comment by jforthofer** [comment]
I think this is complete.
