### ISSUE TITLE
Server security 

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#53]
We need a way to protect the server from being overloaded by too many requests from (1) non-fire users or (2) a single user/device. One option Jason and I discussed was implementing an email verification system where the user's email is tied to their device ID(s). Every user would have to register with a valid email address and we would need to get the unique device ID (we assume all devices must have this?) and associate that with the email address. Only device IDs that have cleared the email verification system would be allowed to submit jobs. If an enabled device became a problem, we would move their device (or all devices tied to their email account) from the 'cleared' list. 

This is just one idea we came up with. Maybe you all have a better idea for this? This is also something we could talk about in person.

**Comment by fspataro** [comment]
Definitely agree with the overall concept... this could get tricky and complex really fast.  

Are we talking about having an "admin" approve users/devices before they can do anything in the app --- new registration notifications to admins, user interface for admins to review, approve, deny, disable registrations, etc? Tracking and figuring out if a user/device is a "problem" means some advanced monitoring on the server as well as some reporting type features.

Short term I think we can implement some sort of simple scheme for server protection but a truly robust implementation seems like a considerable effort and I might have to argue beyond the scope of the original SOW (but that doesn't mean we can't layout a design and plan for it's implementation in the future).

**Comment by nwagenbrenner** [comment]
Yes, something like what you have described is what we have in mind. New devices have to register with a valid email. When the registration comes through we add their email/device ID to a database and set the status to 'unverified'. We (preferably using an automated system) send an email to the supplied address and request a response. If this is all works then the device is approved and the status gets updated in to database to 'verified.' If a device becomes a problem we set it to 'disabled.' So each run submission would require a check to the db to be sure the device ID is in the 'verified' category. Something like this...

We also realize, like you said, that this could get complicated. We think it's important to have some simple scheme in place for the short term. We at least need the app to report back the necessary info to the server (email and device ID) and we can do more/fancier things on the server side later.

**Comment by jforthofer** [comment]
I think this is all pretty much done as of 0.2.3, but lets keep it open until after the final testing phase on the Android and iOS stores where we get others to test.

**Comment by nwagenbrenner** [comment]
This is all covered by our registration and stats logging stuff now.
