### ISSUE TITLE
make the pen more obvious

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#54]
Is there a way to make the pen more obvious (make it stand out a little better)? We think this might make it more intuitive for a first-time user. Can we make the pen and the ink red?

**Comment by CorbyHarkonnen** [comment]
I can definitely change the color of the icon and the 'ink'. I tried making the button larger, but on smaller screens it ended up often causing the footer toolbar to grow in height and misaligned itself.
