### ISSUE TITLE
UI Changes: Layers Dialog

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#55]
Layers

Topo
Satellite
TopoFire
TopoFire (offline)
*For viewing results with no cell coverage. (perhaps in smaller font)

**Comment by fspataro** [comment]
Assuming this list refers to the "basemaps" drop-down?  But keeping the other layers list?  I think there are some other issues related to clean up there.

**Comment by nwagenbrenner** [comment]
Yes, this list refers to the "basemaps" drop-down. We just want to make it clear that TopoFire (offline) is the only option for viewing map imagery without cell coverage. The footnote is an attempt to clarify that this option is for viewing **output** only; some users could think this means they can pan around on a map without cell coverage before doing a run (which isn't the case).
