### ISSUE TITLE
UI Changes: Runs Panel

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#57]
Runs

We think this screen needs to be simplified. We were thinking it would be nice to just display a 'table' here of run names and available options. Something like:

Run1    downloadIcon  infoIcon  deleteIcon
Run2   downloadIcon   infoIcon  deleteIcon
Run3   downloadIcon   infoIcon  deleteIcon

where *Icon are standard/recognizable icons (e.g., download = down arrow with underscore, info = circled I, delete = trash can). The run would be added in the map when it is clicked/highlighted and removed when it is clicked/unhighlighted. The info button could be used to display the run parameters used to create the run (wx model type, vegetation, date of creation, etc.).

**Comment by gcshollow** [comment]
![windninja_new_run_panel](https://cloud.githubusercontent.com/assets/5805929/11375130/c27e3df8-9296-11e5-9fd3-e30bb7a1da70.PNG)

I think this is what the issue was describing, but it looks a little busy to me.  I'm gonna take another crack at it and try implementing a card stack.

**Comment by gcshollow** [comment]
![accordion_expanded](https://cloud.githubusercontent.com/assets/5805929/11380972/832a462c-92b6-11e5-83bb-1c97a35a939b.PNG)
![accordion_collapsed](https://cloud.githubusercontent.com/assets/5805929/11380973/832be3c4-92b6-11e5-9a5f-2a08e4603481.PNG)

This is another option for the runs panel.  The accordion method combines the ease of seeing the list of runs and hides the information until it's selected.  The details of the formatting are flexible, but I think this is a much cleaner way to present the information.

**Comment by CorbyHarkonnen** [comment]
went with option #2 as it was less crowded and easier to navigate
