### ISSUE TITLE
UI Changes: Help

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#60]
Help

This section will include more detail about the overall process (e.g., details about online/offline data, length of time simulations will be stored on the server, how to navigate the application, etc.). We might be able to write this in a way that this same text could be used as the 'application summary' that is provided in the app store – the info the user would read to decide if they want to install the app. I will write this up in a separate document.

**Comment by CorbyHarkonnen** [comment]
do we have verbiage for the help text? The current text is severely out dated and may contain superfluous info at this point.

**Comment by nwagenbrenner** [comment]
How about this:

Navigate (zoom in/out, pan) around on the map until your area of interest is displayed on the screen.

Click the red pen at the bottom of the screen and draw around the area you want to simulate on the map.

When you're satisfied with the selected area, click the check button at the bottom of the screen to continue.

Specify the run name, forecast model, forecast duration, vegetation type, and notification preferences in the "Run Creation" tab and click "Submit" to start your simulation.

Your simulation will be performed on a remote server. If the email or text notification options were selected, you will be notified when your simulation is ready for download. You can also check the status of your simulation in the "Runs" tab at any time. To check the status of a simulation, click on the plus icon next to the run name and click on "Status." 

When your simulation has completed, navigate to the "Runs" tab, click the plus icon next to the run name and click "Status" to confirm the run has completed, and then click "Download." The simulation output will be downloaded to your device.

Click "Plot" in the "Runs" tab to view downloaded output on the map. Click "Layers" at any time on the map to change the base map or add/remove additional layers (e.g., MODIS fire detections). Click "Viewing Options" to turn on/off the legend and forecast time slider or zoom to your simulation extents or display the coarse weather model winds in addition to the WindNinja output.

For more information on WindNinja go to http://www.firelab.org/project/windninja. Contact us at wind.ninja.support@gmail.com with questions or feedback.

**Comment by CorbyHarkonnen** [comment]
Updated in 0.2.3

**Comment by jforthofer** [comment]
I think this looks good, closing.
