### ISSUE TITLE
UI Changes: Quick Start

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#63]
Quick Start  

1. Click the red pen and draw around the area you want to be included in the run.
2. Click the check mark to accept the drawn area.
3. Enter the run information when prompted and click submit.

**Comment by CorbyHarkonnen** [comment]
how do we want to display this info? do we want another button on the 'Settings' screen, or do we want it to display on a 'first-run' situation?

**Comment by nwagenbrenner** [comment]
I think we should display this at start up for the first run done on a new device (or at least by a new user). I don't think we need a separate button for it though, this info is contained in the "Help" page.

**Comment by CorbyHarkonnen** [comment]
Added in 0.2.3
