### ISSUE TITLE
UI Changes: Registration

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#64]
We need a pop-up box that appears the first time the app is launched on a device that requires the user to provide us with an email address. We will verify this email address (somehow, these details still up for discussion) and tie it to their device ID. So at this point, the app should send the email address and the device ID back to the server for the verification process. There will be some delay between the time the email is sent and when the verification process has completed. During this time, the user can use the app (view map imagery, etc), but will not be allowed to submit a run until we have approved them in our system. This screen should pop up every time they open the app until they supply their email address.

Registration (this text may change depending on how we do security stuff)

Thanks for installing WindNinja Mobile! Enter your email address to register WindNinja Mobile on this device. You will be notified via email once your account has been verified by our team.  Thanks!

<text box>
<button> Register

Registration Confirmation

Thanks for registering your install!

We should add a quick start box that pops up every time the application is launched (maybe add a box to check if the user wants to turn off the quick start) and displays the text below.

**Comment by gcshollow** [comment]
![registration](https://cloud.githubusercontent.com/assets/5805929/11248797/5d673d26-8de0-11e5-92f6-66e6a780b589.png)

Registration page design

**Comment by fspataro** [comment]
Short term workflow that will allow for a simple but reliable registration process that will allow devices to be disabled if needed.  We can implement a "Confirm" right away or allow deivices to be automatically "accepted" right now...  Should be a good starting point for discussion on Friday:

Check out this workflow… I’ve got the basics in place for this on the web handler side does it make sense? Seems like it can be implemented easily?

Application opens:
	Registered?
		No ---->
			open registration page 
			send registration: /usfs/windninja/services/registration/register {"name":"fred spataro", "email":"fred.spataro@gmail.com","device":"myphone","platform":"anadroid","version":"1"}
										response: {"account":"fred.spataro@gmail.com","status":"Pending","message":"Registration Pending"}
			save "account" as id, status for other actions
			Proceed to "Yes" check status results (only need to confirm registration if "new accout", existing accounts are either ok or bad)
					
		Yes  ---> 
			Check status? /usfs/windninja/api/account?id=fred.spataro@gmail.com
									Response: {"id":"fred.spataro@gmail.com","email":"fred.spataro@gmail.com","name":"Test","devices":[],"createdOn":"2015-12-10T12:53:58.8193967-07:00","status":"Disabled"}							
				Pending ---> 
					display please confirm registarion, resend email, etc... TBD, continue to app --- disallow sending new requests, can download & use any existing jobs
				Accepted ---> 
					continue to app,
				Disabled ---> 
					display "account has been disabled" message TBD, continue to app --- disallow draw region (see below), can download & use any existing jobs

Draw region click:
	Account status == Accepted?
		No ---> Display message "jobs cannot be created while account status is 'X'" TBD
		Yes ---> continue as currently designed
		
Submitting job 
	Include "account" as part of the job request
		server-side will check account status before queuing job if account is not "Accepted", job status will be 'failed' right away
	Check job status right away
		"failed" ---> display message
		"submitted, etc" ---> proceeded as currently designed

**Comment by CorbyHarkonnen** [comment]
implemented above logic. Will leave this issue open for the time being for future discussions regarding workflow

**Comment by jforthofer** [comment]
Still have one small problem here.  Once a user is registered, the registration screen shouldn't flash up momentarily when the app is opened.

**Comment by CorbyHarkonnen** [comment]
Jason, I thought I had taken care of this with the splash screen (it should hide all the UI initialization, including the drawing of the registration screen).

How long does the splash screen stay up on your device? I may need to shift where/when I'm hiding it

**Comment by jforthofer** [comment]
It seems to vary...  My first test the splash screen seems to be up for about 3 seconds, then maybe 1 second of registration screen plus like 0.2 seconds of what looks like map related things happening.  My second and third tries I didn't notice the registration screen, just about 1 second of the map moving around, zooming into my location I presume.
I wonder if the first try was different because it was getting my GPS location or something like that...?  The second and third tries (immediately after the first) already had a GPS fix maybe?  Either way, it seems the splash screen should stay up a bit longer to hide that, maybe 1.5 more seconds or so?

**Comment by CorbyHarkonnen** [comment]
there is a 'time-out' feature for the splash screen (show splash screen for x milliseconds, then hide), which I can set to whatever we need. however iOS doesn't seem to actually pay attention to this and lets the splash screen stay up indefinitely. I guess I can put a check in to see if we're running iOS and if so, hide it manually, otherwise let it time out. would say 5-6 seconds be long enough?

**Comment by jforthofer** [comment]
Let's try adding 1.5 seconds to whatever it's set to now.

**Comment by CorbyHarkonnen** [comment]
Set splash screen timeout to 8 seconds, verified on my Note 4, will verify with iPad
