### ISSUE TITLE
Typo during registration

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#65]
On the page that reads:
"Registration Complete
    Thank you for registering with
    *NinjaWind* Mobile.
        OK"

NinjaWind should be changed to WindNinja.

**Comment by CorbyHarkonnen** [comment]
Oops. this is text coming from the server. Looks like Fred's dyslexia has struck. I'll see if I can find the spot to fix it.

**Comment by CorbyHarkonnen** [comment]
Closing as this has been fixed with the new server code
