### ISSUE TITLE
Prompt user to enter "WindNinja Mobile Settings"

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#66]
The user needs to be prompted (at least the first time they open WindNinja) to enter their phone number and cell provider so that text messages can be sent.  This happened earlier, but not anymore (maybe this was lost when the registration stuff was coded in).

**Comment by CorbyHarkonnen** [comment]
This was indeed removed with the inclusion of the registration changes, but I can open the settings panel again after the user has registered so they can finish filling in the contact info. (email and name should already be copied over from registration information)

**Comment by jforthofer** [comment]
Sounds good.

**Comment by CorbyHarkonnen** [comment]
Settings panel will now open upon successful registration so the user is able to finish filling in contact information.
