### ISSUE TITLE
Registration page flashes up when WindNinja starts

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#69]
After I've already registered, I open WindNinja and the registration page pops up for about 1 second, then disappears and takes me to the map.  Is there a way we can prevent the registration page from opening briefly like that?

**Comment by CorbyHarkonnen** [comment]
yes and no? I do open the registration page briefly on app load, this is to 'settle' the contents of the panel and initialize any buttons/inputs properly (I actually do this to all the panels/popups for the same reason). It's something weird with the way jQuery builds its elements if the containing DOM element isn't visible. I'll see if there's any other sure-fire way to make sure elements are created/positioned properly on page load.

**Comment by jforthofer** [comment]
OK, I noticed the effect of this same thing I think on the settings page.  The page minimizes, then comes back right after I enter my phone number (and am moving on to enter my cell provider).

It is weird, but don't let this suck up too much of your time trying to fix it...

**Comment by CorbyHarkonnen** [comment]
the flash open/close you notice when entering information in an input is because the window size changes (the keyboard doesn't lay on top of the window, rather it scrunches the size down), and there is a hook to resize panels on window size change (so panels scroll properly). I know its not pretty and can be kind of jarring, I'm still looking to see if there's a way to handle the panel resizing without having to essentially re-initialize the contents of the panel.

**Comment by CorbyHarkonnen** [comment]
I believe I have fixed the issue of the registration screen showing for a second when the app launches. It appears that I accidentally removed the splash screen (which was hiding most of this).

Re-added splash screen, and removed initial open/close of panels.

**Comment by nwagenbrenner** [comment]
This is happening again. If the app is open and I navigate to a different window (but don't close the app), then navigate back to the app, I get this problem.

**Comment by nwagenbrenner** [comment]
This only seems to happen when the back button is used to navigate away from the app.

**Comment by jforthofer** [comment]
Seems to be fixed.
