### ISSUE TITLE
"Offline" map description is a bit confusing.

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#70]
On the "Basemap & Layers" menu, the text:
"*For viewing results with no cell coverage"

is a little confusing to a new user because, at first look, you don't see what the "*" corresponds to.  It almost makes it look like the whole dropdown is "for viewing results with no cell coverage".

I can think of 2 options to make this more clear.

1.  Move the text "For viewing results with no cell coverage" to be on the actual TopoFire (Offline) button, ideally in very small font.

2.  Just remove the text "For viewing results with no cell coverage" and the asterisks.

I guess #1 would be preferred, but if it's too hard or would require a lot of work (restrictions on what the widget can do), lets go with #2.

**Comment by CorbyHarkonnen** [comment]
Yeah, the dropdown widget is kinda picky about what you can include in an option and not have it look out of place (or just straight up break). The original thought was to include the '(Offline)' and '(Online)' tags to differentiate between the options. 

I can also modify the help text to be a bit more descriptive, maybe something like 

'(Offline) denotes that a basemap is usable with no Cell or WiFi coverage.' 

and remove the '(Online)' text from the rest of the basemap options?

**Comment by jforthofer** [comment]
Yeah, I think that will be fine...  remove the asterisk stuff AND the "(Online)" text, also modify the help.  Users should be able to figure that out well enough.

**Comment by CorbyHarkonnen** [comment]
ok, sounds good

**Comment by CorbyHarkonnen** [comment]
removed (Online) tags and updated text to be a bit more helpful
