### ISSUE TITLE
confirmation for run deletion

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#72]
When the delete run button is clicked, there used to be a pop-up window that asked for confirmation before the run was actually deleted. It looks like that check is gone now. Can we add it back in to avoid accidental deletions?

**Comment by CorbyHarkonnen** [comment]
Oops, I had the code in there, accidentally removed it when the run list got changed, will re-add.

**Comment by CorbyHarkonnen** [comment]
re-added confirmation for run deletion
