### ISSUE TITLE
GeoMAC problem

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#73]
It doesn't look like the geomac data is being plotted. Is there a problem here?

**Comment by CorbyHarkonnen** [comment]
This could be because the only portion of the GEOMAC that I'm displaying is current fires and current fire perimeters. I'll double check and make sure the service is coming in properly.

**Comment by jforthofer** [comment]
How can you determine if it is not being plotting...?  I went to the GeoMac web site and I don't see any current fires...

**Comment by nwagenbrenner** [comment]
I thought I downloaded the active fire perimeter kml and there were some. I could be wrong...
