### ISSUE TITLE
Curious about the server side

### ISSUE THREAD

**Issue by liebrand** [firelab/windninja-mobile#75]
Hi there,

I was curious if you have any information about the server aspect of this app?  I've been looking at integrating wind ninja in to a sailing app I'm working on. Effectively integrating it in to a server as well, so if there already is a wind ninja server project (which this mobile code seems to imply), I'd be very interested in the server code...

I couldn't find anything under firelab/ though? Or did I miss it?

/Cheers,
Jelte

**Comment by fspataro** [comment]
Hi Jelte:
We'll be posting the server side component to the mobile app in the next two weeks.  It's basically a python wrapper for the windninja CLI and a restful style web api.

**Comment by liebrand** [comment]
Awesome! That's just what I was after!

Let me know if you want an early beta tester ;-)

**Comment by CorbyHarkonnen** [comment]
closing as this is not an issue. Please see WindNinja-Server directory
