### ISSUE TITLE
SMTP to gmail in AWS does't work

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja-mobile#79]
Google appears to block SMTP requests from AWS ip addresses... implementing via sendmail

**Comment by nwagenbrenner** [comment]
From my tests, it was working for gmail and fs.fed.us accounts, although there were problems with others. You're having issues with gmail too?

**Comment by nwagenbrenner** [comment]
Reggie suggested we might try this. I haven't looked into it very closely yet though.

https://github.com/Rjgoolsby/Ubuntu-Send-Only-Mail-Server/blob/master/server-dns-setup.md

**Comment by fspataro** [comment]
Gmail tests are successful on my end as well. I was having trouble with GCS corporate which has a Barracuda spam/firewall... but I'm not seeing the blocked messages in the queue so it's possible I was mis-typing the email address.

**Comment by fspataro** [comment]
To use sendmail via SMTP on localhost:

Pull the latest version of the code
Update windninjaserver.config.yaml
![image](https://cloud.githubusercontent.com/assets/5933821/14157228/53c21dda-f687-11e5-832f-306c55084331.png)
Update windninjawrapper/config.py
![image](https://cloud.githubusercontent.com/assets/5933821/14157184/284dd9e6-f687-11e5-9ae7-2ce6002aa557.png)

run the deploy script with the "app" and then "config" parameters
