### ISSUE TITLE
Topo map?

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#8]
I'm not sure where the online maps are coming from (open street maps, Google, etc.), but any chance we could add a good topo map with contours, roads, etc. with the online maps (something like the Google Maps "terrain" map)?  Also, is Zack and Allen's server going to be able to do this (provide online maps), or just clip out an offline map of limited extent...?

**Comment by fspataro** [comment]
Yeah, my thoughts were to use the basemaps from Zac/Allen server once they are ready.  Last check it was still building tiles.  So the current set of basemaps are just placeholders

**Comment by jforthofer** [comment]
OK, sounds good...
