### ISSUE TITLE
Change wx model text on phone

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#80]
Can we change the wx model text from NAM CONUS 12km, NAM ALASKA 11.25km, HRRR CONUS 3km to:

CONUS (Short-term)
CONUS (Long-term)
ALASKA

These term will be easier for most users to understand. Conus short-term = HRRR; conus long-term = NAM; Alaska = NAM Alaska.

**Comment by CorbyHarkonnen** [comment]
Changed in 0.2.3

**Comment by jforthofer** [comment]
Looks good, closing this...
