### ISSUE TITLE
Prevent attempted execution of runs outside our DEM extents

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#82]
If possible, this error should be handled immediately upon job submission. Right now, it looks like we try to run a simulation even if the selected domain is outside our DEM extents. It takes a long time for the job to fail (many minutes). Example clip from a job.json file for a South America case:

 {"status": "failed", "account": "jforthofer@gmail.com", "name": "Bad", "messages": ["2016-04-27T17:25:42.340372 | info | job created", "2016-04-27T11:25:44.131911-06:00 | INFO | Initializing WindNinja Run", "2016-04-27T11:25:44    .149642-06:00 | INFO | DEM created", "2016-04-27T11:52:53.207135-06:00 | ERROR | ERROR 1: HTTP error code : 404\nERROR 1: Failed to download file.\nWarning 1: Failed to download forecast, stepping back one forecast run time ste    p.\nERROR 1: Operation timed out after 20000 milliseconds with 7685579 bytes received\nERROR 1: Failed to download file.\nWarning 1: Threaded download failed, attempting serial download for hrrr.t16z.wrfsfcf04.grib2\nERROR 1: T    oo many points (441 out of 441) failed to transform,\nunable to compute output bounds.\nERROR 1: IReadBlock failed at X offset 0, Y offset 4\nERROR 1: GetBlockRef failed at X block offset 0, Y block offset 4\nERROR 1: Too many     points (441 out of 441) failed to transform,\nunable to compute output bounds.\nERROR 1: IReadBlock failed at X offset 0, Y offset 4\nERROR 1: GetBlockRef failed at X block offset 0, Y block offset 4\nERROR 1: Too many points (    441 out of 441) failed to transform,\nunable to compute output bounds.\nERROR 1

**Comment by fspataro** [comment]
Job wrapper code now checks if job bounding box is within a simplified geometry of CONUS and AK, see picture.  This geometry is embedded as a base64 string of 'well known binary' so it can be easily updated.  We can get more complex or detailed with the geometry but this cover it pretty well.  

![image](https://cloud.githubusercontent.com/assets/5933821/15160099/5536ecba-16b5-11e6-9f89-53e62fe88e51.png)

**Comment by nwagenbrenner** [comment]
Ideally, when this fails the error should contain some info on the failure, explaining that the chosen area is outside of our DEM extents. We can add this later.
