### ISSUE TITLE
Times not being handled correctly?

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#84]
A 12 hr duration NAM run at 1:45 on April 27 generates the output for 1, 6-23 and 0-1 on April 28. But only these json files are created:

-rw-r--r--  1 root     root      4075546 Apr 27 19:38 dem_04-27-2016_2300_134m.json
-rw-r--r--  1 root     root      4078989 Apr 27 19:38 dem_04-27-2016_2100_134m.json
-rw-r--r--  1 root     root      4074684 Apr 27 19:38 dem_04-28-2016_0100_134m.json
-rw-r--r--  1 root     root      4077021 Apr 27 19:39 dem_04-27-2016_2200_134m.json
-rw-r--r--  1 root     root      4085630 Apr 27 19:39 dem_04-27-2016_2000_134m.json
-rw-r--r--  1 root     root      4088647 Apr 27 19:39 dem_04-27-2016_1900_134m.json
-rw-r--r--  1 root     root      4074903 Apr 27 19:39 dem_04-28-2016_0000_134m.json

**Comment by fspataro** [comment]
Can you look in the windninja folder in that job and see what times were downloaded and datasets created.  I think windninja only generates forecasts starting from the time it can download and often that time is in the past.  So if you ask for 12 hours, you only get 12 items from the last forecast download wihch might only be 8 hour from the current time if the forecast is 4 hours old.  It generating all 12 outputs but I didn't think the user cared about dataset that are past the current time so I skip converting them to save download and performance.

**Comment by nwagenbrenner** [comment]
Created datasets are below (April 27 hours 6-23, April 28 hours 0-1). Maybe the issue is UTC vs. local time? Note that the times included in the WindNinja output are in DEM local time.

-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_0600_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_0600_134m.shp
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_0600_134m.dbf
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_0600_134m.prj
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_0900_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_0900_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_0900_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_0900_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_1200_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_1200_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_1200_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_1200_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_1500_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_1500_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_1500_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_1500_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-28-2016_0000_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-28-2016_0000_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-28-2016_0000_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-28-2016_0000_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_2000_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_2000_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_2000_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_2000_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_1800_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_1800_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_1800_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_1800_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_2200_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_2200_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_2200_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_2200_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_0700_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_0700_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_0700_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_0700_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_1000_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_1000_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_1000_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_1000_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-28-2016_0100_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-28-2016_0100_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-28-2016_0100_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-28-2016_0100_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_1300_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_1300_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_1300_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_1300_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_1600_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_1600_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_1600_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_1600_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_2100_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_2100_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_2100_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_2100_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_1900_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_1900_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_1900_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_1900_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_2300_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_2300_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_2300_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_2300_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_0800_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_0800_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_0800_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_0800_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_1100_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_1100_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_1100_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_1100_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_1400_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_1400_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_1400_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_1400_134m.dbf
-rw-r--r-- 1 root root 157828 Apr 27 19:38 dem_04-27-2016_1700_134m.shx
-rw-r--r-- 1 root root 552148 Apr 27 19:38 dem_04-27-2016_1700_134m.shp
-rw-r--r-- 1 root root    505 Apr 27 19:38 dem_04-27-2016_1700_134m.prj
-rw-r--r-- 1 root root 808517 Apr 27 19:38 dem_04-27-2016_1700_134m.dbf

**Comment by fspataro** [comment]
Thanks, that's probably it.  I'm sure I assumed the output times were in the same clock as the input forecasts times ... 

hmmm but if they're local to the DEM that's going to make it tricky to figure out which ones to return since the server code doesn't know jack about the DEM time-zone... hence the reason i assumed they were UTC.  

Can we make windninja output times in UTC? 

I'll probably just scratch the code to filter for future results and return everything.

**Comment by nwagenbrenner** [comment]
The filtering code would have to know about DEM local time (since that's what the user cares about), so maybe returning everything is the best option for now? Jason?

**Comment by jforthofer** [comment]
Seems like there are 2 options for us at this point (easy, quick options that is):
1.  Just return everything as Fred mentioned.
2.  Modify the WindNinja code so that it writes UTC times in the file names (Fred, I assume you are parsing the output filenames to get the time?).  This could be only done when the cmake setting MOBILE_APP=ON, so desktop WindNinja still works the same as always.

One other thing to keep in mind, we need to make sure that the time displayed in the mobile app for the simulation you're currently viewing is correct and is in local time if at all possible.  Our users won't like UTC here.  How is this currently working Fred?  UTC?

**Comment by CorbyHarkonnen** [comment]
currently, in the app, I'm parsing out the date/time from the file name and using that for display (as well as sorting the results properly), so if the file names get changed to UTC, I'd have to do some manipulation under the hood to get 'local' time.

**Comment by jforthofer** [comment]
OK, so it sounds like we'll need to come up with a solution for all this since I think it would be bad to make our users do the math to convert from UTC to local time.  Probably lots of different ways to tackle this, but what is best and least work?  Can we have a quick call to talk?  I'll send a separate email for responses from people.

**Comment by jforthofer** [comment]
After further examination, our short term solution will be to just send the phone all output files made by WindNinja on the server.  The WindNinja filenames will stay in local time.

Someday we could write code to only send the future forecast files (saving processing, bandwidth, and memory) and still display on the phone's map the local time for the forecast.

**Comment by fspataro** [comment]
Code is updated to send all results... 'past' filter code is commented out in the source for later if we want.

**Comment by nwagenbrenner** [comment]
Seems to be fixed.
