### ISSUE TITLE
Mis-match between model type and duration

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#85]
At first launch, CONUS (Short-term) is displayed but the time duration slider goes out to 36, which is not correct. It should end at 15. If you choose another model option, then switch back to CONUS (Short-term), the slider is correct (ends at 15).

**Comment by CorbyHarkonnen** [comment]
I think this is an artifact of my moving around the options, the default used to be Long-term and had the UI pre-wired for its length.

**Comment by CorbyHarkonnen** [comment]
fix for this is checked in, will need to make another build when ready for testing.
