### ISSUE TITLE
Provide more info on failures related to DEM extents

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#86]
When a run fails because it is outside of the DEM extents, we should notify the user of the cause of the failure. Right now we just report that the run "Failed."

**Comment by fspataro** [comment]
The errors messages are being returned in the job json so it should be straight-forward to display them in the app.

**Comment by CorbyHarkonnen** [comment]
Errors should be displaying in the app (since 1.3?)
