### ISSUE TITLE
Unclear what happens during download if phone sleeps

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#89]
If you are in the middle of a run download and push your power button to turn off the screen or go to sleep, the download progress bar seems to be frozen when you turn the screen back on. After restarting windninja it seems that the download did complete.

**Comment by CorbyHarkonnen** [comment]
This appears to just be a UI issue. I will have to dig a bit further into it to see how to resolve 'sleep' issues gracefully.

**Comment by CorbyHarkonnen** [comment]
verified locally, downloads appear to complete even when phone is in 'sleep' mode. adding code to update the UI and remove the download dialog on resume.
