### ISSUE TITLE
Problems when the ocean is in the domain

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#90]
Simulations fail when the ocean is in the domain. Most likely no data values in the elevation file. This could be pushed to 1.1 if no easy fix is possible.

**Comment by nwagenbrenner** [comment]
What was the name of the job that failed?

**Comment by fspataro** [comment]
I have a test case for a location fully in the ocean.  It's the 1c11111... job.  It falls within our basic AOI so it passes that test.  WindNInja CLI spits out: 
```
ERROR 1: Failed to Find timezone, 
Could not detect timezone.   
```

**Comment by nwagenbrenner** [comment]
We need to set `export NINJA_FILL_DEM_NO_DATA=ON`. This was the issue for Jason's "water" case (job 6490e15b142448578059ebe487e2d496). There were no data values in the DEM over the water. I don't see the 1c1111... job on AWS and have not seen the time zone detection failure.

**Comment by fspataro** [comment]
The 1c11111...job is in the local repo Data/job folder.  I didn't think there was a reason to copy these edge cases to the deployment folder.  You can run the edge case jobs by opening the command prompt at [_local repo folder_]/Src/windninjawrapper 

`python windninja.py 1c111111111111111111111111111111 -i -v -d`

**Comment by nwagenbrenner** [comment]
The dem generated by that case contains only no data values (presumably because it only covers water). It's probably not necessary to account for DEMs that only cover water since there won't be any fires in those domains. Setting NINJA_FILL_DEM_NO_DATA will account for cases where there are mixtures of water and land, so is probably all that needs to be done. Unless I'm missing something. Just to be clear, I think the time zone error is probably a false alarm, the real issue is the no data values.

**Comment by fspataro** [comment]
I think the time zone message is a real error that comes before the NO DATA error.  There's a time zone shapefile in the windninja/data/tz_world.zip.  I'm guessing this is used to "auto" figure out the time zone.  It only covers the land masses, so if you're in the ocean, you can't use this feature set to determine your time zone... probably not an issue for wildfires ... but the time zone error is probably not "false" ... 

![image](https://cloud.githubusercontent.com/assets/5933821/15486820/a1a05ef6-2105-11e6-899c-ca001d459363.png)

**Comment by nwagenbrenner** [comment]
I'm aware of how the time zone detection works, I'm just not sure we need
to worry about domains that only cover the ocean. I also thought the error
text might have been a copy paste error, but didn't look into it yet. We'll
check it out. Regardless, the fill dem option I mentioned previously should
be set.

**Comment by jforthofer** [comment]
Yeah, sounds like you're both correct.  Kyle wrote the timezone autodetect code, but if I remember correctly he uses the center point of the DEM to see which timezone it's in.  So if the center is outside those polygons it will give an error.  One quick fix that would solve *most* problems would be to modify that code to check to see if ANY of the corners are in a timezone.  Probably other possibilities for fixes as well.

**Comment by ksshannon** [comment]
I try the point first, then build up to 5 concentric 0.2 degree buffers and check for intersection with features in the shape file.  If more than one intersection is reported, I take the first one returned by OGR_L_GetNextFeature()

**Comment by fspataro** [comment]
I marked it 'waiting for verification'.  Once the cli is rebuilt, one of you can close this out, if there's nothing else to handle.  Probably should add these flags to the list of specific items for the cli build.  Right now the readme has the link to the stock linux build notes plus the note to include the python gdal bindings.  I think there's a few other flags that are must add at this point...

**Comment by nwagenbrenner** [comment]
The fill dem option is a runtime option. It just needs to be set in
windninjawrapper when the CLI is fired. I don't think we need to rebuild
the CLI. Unless there's something else we forgot.

**Comment by jforthofer** [comment]
So if what Kyle said is working, and I'm guessing it is, then my "water" simulation should have correctly found a time zone...  It's weird it gave a time zone error.  It was right on the west coast of the US and included some ocean and some land.  There would have definitely been a problem with no_data values in the DEM, but seems like it would have found the time zone.  Natalie, you might have to track this down a little more to be sure we fix this...?

**Comment by nwagenbrenner** [comment]
Jason, your water case didn't have the time zone error. Only Fred's ocean
only case had that problem, which is why I said I don't think we need to
worry about it. I think we're good.

**Comment by nwagenbrenner** [comment]
Jason, if this still doesn't make sense, let's talk tomorrow. I don't think
I can be any clearer in email.

**Comment by jforthofer** [comment]
Got it, I thought mine threw the time zone error.  Yeah, it does sound like we're good.  Just need to add the fill no_data option to the cli input file, which is a runtime switch.  Good, that's easy...
