### ISSUE TITLE
Modify scale bar

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#91]

**Comment by CorbyHarkonnen** [comment]
scale bar added in 0.2.6.

currently, if the legend or time slider are opened, they will cover the scale bar. I will leave this as is for the time being, but if somebody has an idea of a 'better' place to put the scale bar or legend, it should be fairly quick to update.

**Comment by jforthofer** [comment]
Thanks for adding this, I really like it.  Just have a few comments/ideas.  To me, it's not a big problem when the time slider covers the scale bar because you can still pretty much see it.  But the legend completely covers it (on my phone when the screen is vertical).  I think at the least we should put the legend on one side of the screen and the scale bar on the other.  I guess I don't have a preference which one is on which side.
Last, is it possible to display the distance in miles instead of kilometers?

**Comment by CorbyHarkonnen** [comment]
scalebar set to Miles
