### ISSUE TITLE
Be tolerant of TopoFire server down

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#92]
I want to be sure we're tolerant of the TopoFire server being down. Another issue/ticket made sure it works in Alaska were there is no TopoFire coverage, but it also needs to work in CONUS when the server is down.

**Comment by fspataro** [comment]
This is already covered.  If any requested specific tile fails to downloaded from a source for any reason, a blank "tile not available" image is created in it's place.  If a tile package is requested, a full set will always be created regardless of the state of the source.

**Comment by jforthofer** [comment]
Awesome, thanks Fred!
