### ISSUE TITLE
Lost connection freeze

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#94]
When I have the app open on my phone, but put it to sleep and walk around for a while and apparently go in and out of service, and then wake my phone the app is frozen with a message that says "Connection status: lost connection".

**Comment by CorbyHarkonnen** [comment]
I have removed the alert message when the phone loses internet connection, online features will still be disabled until the phone reconnects to a network, but there should be less chance of the phone freezing due to the alert dialog being left open.
