### ISSUE TITLE
Legend messed up when screen is rotated

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#95]
When I plot vectors and turn on the legend, then rotate my phone/screen to (like from "portrait" to "landscape"), the legend doesn't get drawn in the correct location, it ends up in the middle of the screen.  If the legend is then turned off, then on, it plots back in the correct location.

**Comment by CorbyHarkonnen** [comment]
hiding and re-showing legend on screen rotate (solves the issue of the legend displaying in the center of the screen)
