### ISSUE TITLE
Output for multiple time steps not ordered correctly

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja-mobile#97]
In at least some cases on iOS there is no apparent order when scrolling from left to right on the time slider. This appears to only happen on iOS. 

![3](https://cloud.githubusercontent.com/assets/3696653/15941252/80a45f60-2e3c-11e6-9bdc-bf454ee09dc1.jpg)

![4](https://cloud.githubusercontent.com/assets/3696653/15941256/84aca41e-2e3c-11e6-8d5b-8b8cee0ced9a.jpg)

![5](https://cloud.githubusercontent.com/assets/3696653/15941275/93841cec-2e3c-11e6-8a30-2b8988431382.jpg)

**Comment by CorbyHarkonnen** [comment]
I have a feeling this has to do with the way iOS handles date objects in javascript (that is how I'm ordering the run outputs), I'll take a look at this.

**Comment by CorbyHarkonnen** [comment]
Properly ordering outputs on iOS now
