### ISSUE TITLE
Links in Help don't seem to work

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#98]
On the Help page, the web links at the bottom don't do anything when you click on them.  The desired behavior would be to open the web page and open the mail client to send an email.

**Comment by fspataro** [comment]
Tory,
Are we missing the href location for these links or is app being sandboxed from opening them?

Jason, what URL should be loaded for the Help link?

**Comment by CorbyHarkonnen** [comment]
I just verified this last night on my phone. the links are there (and are wired properly for 'normal' html usage), but it looks like cordova doesn't open a browser or email client when clicked like on a desktop or standard website. I took a look, and there appear to be plugins that enable these native phone functions, I'll just need to add them and test.

as a note: these would leave the app when the links are clicked and open either the standard email client or web browser, when done with whatever action the user was performing, they would then have to either re-launch the app, or use the task manager to switch back to the running app.

**Comment by fspataro** [comment]
I figured it was a sandbox issue.  Could we have the help link open in another app view page?

**Comment by jforthofer** [comment]
The link that's there now is good for now.  Natalie, what did we ever decide on the WindNinja-mobile web page?  I think we decided we're going to have another page, right (as opposed to just talking about the mobile app on the WindNinja desktop's web page)?  If that's the case, we should like to this.  Natalie, could you get them the proper link then?  Hopefully Audrey can make a redirect page like WindNinja at:
http://www.firelab.org/windninja-mobile
or something similar...

**Comment by nwagenbrenner** [comment]
Should be http://firelab.org/project/windninja-mobile

**Comment by CorbyHarkonnen** [comment]
wired up clicks on help links. the web link will open in the system browser and the email link will open the default mail application.
