### ISSUE TITLE
Plot time slider and legend at same time

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja-mobile#99]
Right now, the time slider and legend are mutually exclusive, meaning they can't both be turned on at the same time.  I think this was done like this just because of limited screen size?
I think it might be better if both could be turned on at the same time.  Problem is that right now they would overlap on most phones.  To fix this, could we move the time slider to the top center, right under where the date/time is displayed?  This might be a little more intuitive to what the slider does anyway...
If this all works fine, we should also consider defaulting both of these to be turned on when a person first plots a simulation.  This idea came about from watching a first time user trying to figure out how to work the app.  These changes would make things more intuitive I think.

**Comment by fspataro** [comment]
Related #47

Makes sense... i think this goes to whole redesign of the time slider.  Rather than a slider, other UI
options:

1. some set of buttons and text at the top like:

[<<] 6-13-16 8:00AM  (3 of 12) [>>] 

2. drop down list:

 6-13-16 8:00AM  (3 of 12) [v]
       - 6-13-16 6:00AM
       - 6-13-16 7:00AM
       - 6-13-16 8:00AM
       - 6-13-16 9:00AM
       - etc

3 drop down with slider or buttons or etc

**Comment by CorbyHarkonnen** [comment]
I had a thought on this as well, what if we added a 'play/pause' button (top or bottom, doesn't matter) that would 'play' through the time steps automatically (possibly in a loop, also with the ability to pause at any point), with forward/backward buttons that step in single increments?

**Comment by jforthofer** [comment]
Yeah, the standard on web pages that plot forecast weather model data is to have the play/pause and step capability.  The only thing to worry about here I think is the small size of typical mobile screens.  I like Fred's #1 above, but would like to hear what Natalie and others think...

**Comment by nwagenbrenner** [comment]
I like the slider, it's just hard to navigate when there are many time steps. It's useful if you want to immediately scroll to the last time step, for example. I like the idea of moving the time slider to the top of the screen under the datetime display. To improve time slider navigability, maybe arrows could be displayed on either end of the slider bar to allow advancing forward/backward one time step. Something like this:

12/15/2015, 2:00:00 PM
[<<]---=-----------------[>>]

This is my preference, but I don't care too much. Any of the options described are probably fine.

**Comment by jforthofer** [comment]
I like Natalie's idea with just adding the arrows.  It will take up minimal screen space, but I think pretty much give all the desired behavior.

**Comment by CorbyHarkonnen** [comment]
fixed in v1.0.3 - moved time navigation to top of screen and allowed both to be open at once (see also #138)
